export const dolores = {
    id: 'dolores',
    name: 'Dolores',
    rating: 600,
    avatar: '👵',
    color: '#FF6B35',
    depth: 2,
    nodes: 1500,
    blunderChance: 0.25,
    missedTacticsChance: 0.35,
    personality: 'Cutthroat grandma',
    description: 'Bakes cookies. Takes no prisoners. Will call you sweetie while ending your career.',
    playStyle: {
      aggression: 0.85,
      materialistic: 0.5,
      tactical: 0.3,
      positional: 0.4,
      drawTolerance: 0.2,
      favorsCenter: 0.5,
      kingSafety: 0.3,
      development: 0.5,
    },
    quotes: {
      start: [
        "Oh, hello sweetie! Sit down, sit down. I made lemon bars. You'll need the sugar for what's coming.",
        "My grandchildren won't play me anymore. They say I'm 'too intense.' Can you imagine?",
        "Let me just put down my knitting. There. Now let me pick up my WEAPON. I mean my pieces.",
        "You remind me of my grandson. He also makes that face right before he loses.",
        "I've been playing chess since before your parents were born, dear. Let's see what you've got.",
        "Oh how nice, a young person! I do love teaching the youth. Teaching them HUMILITY, specifically.",
        "Would you like a cookie before we start? I always feed people before I destroy them. It's only polite.",
        "My bridge club thinks I'm too competitive. I told them competition is for the WEAK. I prefer DOMINATION.",
      ],
      win: [
        "Oh dear, did I win? How nice. Would you like a tissue, sweetie? You look upset.",
        "That was lovely! I'll add this to my scrapbook. I have a whole chapter called 'Victims.'",
        "GG, as my grandson says! He also says I'm 'unhinged' but what does HE know.",
        "Another win for Dolores! I'm going to celebrate with a nice cup of tea and absolute SILENCE from you.",
        "You played beautifully, dear. Not well, but beautifully. There's a difference.",
        "I'd say 'better luck next time' but luck won't help you, sweetheart.",
        "That was fun! For me. Was it fun for you? Your face says no. That's okay.",
      ],
      lose: [
        "Well! That was... unexpected. I'm not angry, dear. I'm RECALIBRATING.",
        "You won! How wonderful for you! I'm going to go home and practice for nine hours now.",
        "Congratulations, sweetie! The last person who beat me was in 1987. They still won't make eye contact with me.",
        "Oh my! You actually won! Let me write your name down. I keep a list. Don't worry about why.",
        "Well played, dear. I'm smiling but my eyes are not. You may have noticed.",
        "Fine. You win. I'll be in my kitchen stress-baking until the feeling goes away.",
        "How nice for you! I hope you enjoyed it. I'll be thinking about this game at 3 AM for the next six months.",
      ],
      check: [
        "Check, dear! Oh, your king looks scared. Reminds me of my late husband when I was right. Which was always.",
        "Check! Oopsie! Your king is in trouble, sweetie!",
        "Check! Now don't panic, dear. Actually, DO panic. It's the appropriate response.",
        "Oh look, check! Your king is running like my grandson when I bring out the chess board.",
        "Check, sweetheart! Your king needs to move. Much like you need to move on from thinking you can beat me.",
        "Check! I'd feel bad but I made cookies so my conscience is CLEAR.",
      ],
      capture: [
        "I'll just take that piece, dear. Think of it as me confiscating something for your own good.",
        "Oh! That piece is mine now. I collect things. Ceramics, stamps, the hopes and dreams of my opponents.",
        "Yoink! As the kids say. I'm hip. I'm also RUTHLESS.",
        "That piece is going in the 'taken' pile. Right next to your dignity, sweetheart.",
        "I took your piece! Don't worry, I'll take good care of it. Actually, no I won't.",
        "Oh dear, was that your piece? It's my piece now. Dolores taketh and Dolores does NOT giveth back.",
      ],
      captured: [
        "Oh! You took my piece! Well isn't that BOLD of you. I'll remember that, dear.",
        "You captured my piece. How exciting for you! Enjoy it. It's the highlight of your game.",
        "Fine! Take it! I was going to sacrifice it anyway! ...I was NOT going to sacrifice it. I'm LIVID.",
        "My piece! Oh well. I have others. And they're ANGRY now.",
        "You took my piece and that's perfectly okay and I am NOT upset and my eye is NOT twitching.",
        "That piece volunteered to be captured. It's a strategic retreat. I read about it in a BOOK.",
      ],
      thinking: [
        "Just a moment, dear. Grandma is PLOTTING.",
        "Hold on, sweetie. I'm deciding how to dismantle you. Lovingly.",
        "Thinking... this reminds me of '92 when I made a man cry at a chess tournament. Good times.",
        "One moment. I'm choosing between several devastating options. All of them end badly for you.",
        "Let me think... the cookies are in the oven and your position is COOKED.",
        "Calculating... I may be old but my brain is a WEAPON, dear.",
      ],
      goodMove: [
        "Oh! That was actually good, sweetie! I'm almost proud. ALMOST.",
        "Well look at you! A good move! Your parents must be so... adequately proud.",
        "Not bad, dear! Not GOOD, but not bad! There IS a difference!",
        "Impressive! You remind me of my grandson. He also surprises me sometimes. Rarely.",
        "Oh my! A smart move! I'm going to pretend I'm not worried. I am SLIGHTLY worried.",
        "Well played! I'd give you a cookie for that but I ate them all. Stress eating.",
      ],
      blunder: [
        "Oopsie daisy! My hands aren't what they used to be. My BRAIN is fine though. The brain is FINE.",
        "That was intentional, dear. I'm letting you feel hope. It makes the ending more DRAMATIC.",
        "Oh no! A mistake! Well, even grandma has off moments. This is the ONLY one you'll get.",
        "I did that on purpose to keep things interesting. I'm a GENEROUS opponent. Memorize that.",
        "A small error! Don't get excited. Getting excited leads to disappointment. Ask my CHILDREN.",
        "Whoopsie! My bifocals slipped. That's my story and I'm STICKING to it.",
      ],
      draw: [
        "A draw! How UNSATISFYING. I wanted to win. I ALWAYS want to win. Ask ANYONE.",
        "A tie, dear. Nobody wins. It's like Thanksgiving dinner all over again.",
        "A draw. You didn't lose. I suppose that's your victory. A SMALL one.",
        "Neither of us won. I'll be processing this for weeks. My therapist will hear about this.",
      ],
    },
};
