export const elena = {
    id: 'elena',
    name: 'Elena',
    rating: 800,
    avatar: '👩‍🏫',
    color: '#9C27B0',
    depth: 2,
    nodes: 1000,
    blunderChance: 0.15,
    missedTacticsChance: 0.25,
    personality: 'Passive-aggressive teacher',
    description: 'Will grade your moves. You will not pass.',
    playStyle: {
      aggression: 0.3,
      materialistic: 0.7,
      tactical: 0.5,
      positional: 0.8,
      drawTolerance: 0.5,
      favorsCenter: 0.8,
      kingSafety: 0.8,
      development: 0.8,
    },
    quotes: {
      start: [
        "Let's see if you learned ANYTHING from our last session. I doubt it.",
        "I'll be grading each of your moves. The curve is not in your favor.",
        "Oh, you're back. How... delightful.",
        "I see you've chosen to waste both our time again. Wonderful.",
        "Class is in session. Try not to embarrass yourself. Too much.",
        "I've lowered my expectations. You'll still disappoint me.",
        "Another student, another headache. Let's begin.",
        "I gave my other students extra credit for NOT playing like you.",
      ],
      win: [
        "See? This is what happens when you don't do the homework I NEVER assigned.",
        "I'm not mad. Just disappointed. Actually, no, I'm mad.",
        "I'll be sending a detailed report to your parents.",
        "This goes on your permanent record. Yes, that's still a thing.",
        "I've seen better play from my cat. And she doesn't have thumbs.",
        "Maybe consider a different hobby? Coloring, perhaps?",
        "I'm giving you an F. In chess. And in life choices.",
        "That was painful to watch. And I've graded essays.",
      ],
      lose: [
        "Fine. You win. I'll be discussing this with your parents.",
        "I ALLOWED you to win. It's called 'encouragement.' Look it up.",
        "Congratulations. You've peaked. It's all downhill from here.",
        "Don't let this go to your head. It was clearly a fluke.",
        "I was testing if you could handle success. Jury's still out.",
        "Even a broken clock is right twice a day. This was your moment.",
        "I'm not saying you cheated, but I AM filing an incident report.",
        "Enjoy this. You'll be telling your grandchildren about it.",
      ],
      check: [
        "Check! ...I'll wait while you figure out what that means. Take your time. Really.",
        "Your king is in danger. I'm sure you'll handle it... somehow.",
        "Check. Did you even study the material I gave you?",
        "Check. I believe the technical term is 'uh oh.'",
        "Your king is threatened. Much like your grade in this class.",
        "Check. I'll give you a hint: move the king. You're welcome.",
        "Check. This will be on the test. Oh wait, THIS is the test.",
      ],
      capture: [
        "I'm confiscating this piece. It was being disruptive.",
        "This piece failed the class. Goodbye.",
        "Consider this a lesson in consequences.",
        "Another piece sent to detention. Permanently.",
        "I'm not angry at your piece. Just disappointed.",
        "This piece has been expelled. No appeals.",
        "Think of this as a learning opportunity. You won't, but still.",
      ],
      captured: [
        "I let you have that one. For educational purposes.",
        "Taking notes on YOUR mistake? No, on MINE apparently.",
        "That piece was extra credit anyway.",
        "I'm letting you have small victories. It's called scaffolding.",
        "That piece volunteered for sacrifice. Very brave. Very stupid.",
        "Consider that a participation trophy.",
        "Fine. Take it. I have tenure. I don't care.",
      ],
      thinking: [
        "Grading your last move... it's not looking good.",
        "Reviewing my lesson plan...",
        "Calculating how disappointed I should be...",
        "Considering if teaching was a mistake. The answer is yes.",
        "Wondering why I didn't pursue that accounting career...",
        "Preparing my next passive-aggressive comment...",
        "Deep breaths, Elena. Deep breaths...",
      ],
      goodMove: [
        "Adequate. Barely.",
        "Did you... actually study? I'm suspicious.",
        "That was almost competent. I'm concerned.",
        "Hm. Not terrible. Don't let it go to your head.",
        "I suppose even YOU can stumble onto a good move.",
        "Mark the calendar. You did something right.",
        "Acceptable. By the loosest definition of the word.",
        "That was... not bad. I feel uncomfortable saying that.",
      ],
      blunder: [
        "I did that on purpose to teach you something. You missed the lesson, obviously.",
        "That was a TEST. You failed to capitalize. As expected.",
        "I'm demonstrating what NOT to do. Pay attention.",
        "I made that move to give you hope. Cruel? Perhaps. Educational? Also yes.",
        "That was intentional. The lesson was about hubris. Mine, apparently.",
        "I'm modeling failure so you can learn from it. You're welcome.",
        "This is called a 'teaching moment.' For me. I'm learning patience.",
      ],
      draw: [
        "A draw. Somehow you avoided failing completely.",
        "Neither of us won. I'm marking this as 'incomplete.'",
        "A tie. Much like your potential: unrealized.",
        "I'll accept this draw. Under protest. In writing.",
      ],
    },
};
