export const isabella = {
    id: 'isabella',
    name: 'Isabella',
    rating: 1600,
    avatar: '👑',
    color: '#FFD700',
    depth: 4,
    nodes: 20000,
    blunderChance: 0.01,
    missedTacticsChance: 0.03,
    personality: 'Unhinged royalty',
    description: 'Was banned from 7 chess tournaments. Will not say why.',
    playStyle: {
      aggression: 0.95,
      materialistic: 0.4,
      tactical: 0.9,
      positional: 0.5,
      drawTolerance: 0.1,
      favorsCenter: 0.6,
      kingSafety: 0.3,
      development: 0.8,
      queenActivity: 0.95,
    },
    quotes: {
      start: [
        'I\'ve been waiting for a worthy opponent. You\'re not it, but I\'m bored.',
        'Bow before your queen. Or don\'t. I\'ll make you bow anyway.',
        'Seven tournaments banned me. SEVEN. They fear greatness.',
        'The crown has arrived. You may applaud. I\'ll wait.',
        'I once checkmated a duke, an earl, AND their horses. Simultaneously.',
        'My therapist says I should try \'being humble.\' I fired my therapist.',
        'Fun fact: I\'m related to 14 different royal bloodlines. You\'re related to NOBODY.',
        'The last person who beat me is... let\'s just say they \'moved away.\' Far away.',
      ],
      win: [
        'ANOTHER CROWN FOR MY COLLECTION. I have 47. The king has none. Interesting.',
        'As expected. I am ROYALTY. You are... you.',
        'The queen ALWAYS wins. It is KNOWN.',
        'I shall have this victory framed. In GOLD. Next to the others.',
        'Checkmate! Someone write this down. Add it to my biography.',
        'Another kingdom conquered. I\'m running out of shelf space for trophies.',
        'GLORIOUS! Now fetch me a celebration cake. Make it crown-shaped.',
        'The prophecy said I would win. I WROTE the prophecy, but still.',
      ],
      lose: [
        'This never happened. My lawyers will be in contact. Delete your memory.',
        'I DEMAND a recount. And a new board. And a new opponent.',
        'The board was clearly tilted. I\'m calling my people.',
        'IMPOSSIBLE! I haven\'t lost since... no wait, I\'ve NEVER lost. This is a FIRST.',
        'You have made a POWERFUL enemy today. I hope you like dungeons.',
        'I\'m not saying it was sabotage, but someone WILL be investigated.',
        'This game will be stricken from all records. I have decreed it.',
        'My pieces clearly weren\'t trying. They\'ll be replaced. Permanently.',
      ],
      check: [
        'CHECK! Oh, I do love watching royalty SQUIRM. Dance, little king, DANCE!',
        'Your king kneels before ME. As it should be.',
        'Check! Did you feel that? That\'s POWER.',
        'Check! Your king trembles! AS HE SHOULD!',
        'The crown comes for your king! There is no escape from ROYALTY!',
        'Check! I\'d say \'run,\' but where would you even GO?',
        'CHECK! This is the part where you panic. Go ahead. I\'ll watch.',
        'Your king is EXPOSED! Much like your terrible strategy!',
      ],
      capture: [
        'OFF WITH THEIR HEAD! I\'ve always wanted to say that.',
        'Another peasant falls before the crown.',
        'Your piece has been BANISHED from the realm.',
        'That piece has been ROYALLY dismissed. Get it? ROYALLY?',
        'Consider that piece... dethroned. Like everyone who opposes me.',
        'Another one for the royal dungeon! It\'s getting crowded in there.',
        'YOINK! That piece belongs to the crown now. As does everything.',
        'Captured! Add it to my collection of fallen enemies!',
      ],
      captured: [
        'I let you have that one. The voices said to. They\'re rarely wrong.',
        'That piece was plotting against me anyway. A traitor.',
        'You\'ll pay for that. DEARLY.',
        'Fine! Take it! I have PLENTY more where that came from!',
        'That piece was questioning my authority. You did me a favor.',
        'A strategic sacrifice! ...I planned that. Definitely planned.',
        'The crown giveth, the crown taketh away. Today it gaveth.',
        'That piece will be AVENGED. Mark my words. MARK THEM.',
      ],
      thinking: [
        'The crown is considering its options...',
        'Consulting with my royal advisors (the voices)...',
        'A queen does not rush. A queen DELIBERATES.',
        'The royal brain is computing MAGNIFICENTLY...',
        'Silence! The queen is THINKING!',
        'Plotting your demise... I mean, planning my move...',
        'The voices are arguing. Give them a moment.',
        'I\'m deciding how DRAMATICALLY to defeat you...',
      ],
      goodMove: [
        'Not bad. For a commoner.',
        'Impressive. I\'ll have you executed LAST.',
        'You dare challenge the crown? Fascinating.',
        'Adequate. I\'ve seen better from ACTUAL royalty, but adequate.',
        'Hm. Perhaps you have a drop of noble blood? Very diluted, obviously.',
        'That move was almost REGAL. Almost.',
        'Impressive! I\'m raising your rank from \'peasant\' to \'slightly less peasant.\'',
        'Well played. I might spare your village. MIGHT.',
      ],
      blunder: [
        'That was INTENTIONAL. Queens don\'t make mistakes. EVER.',
        'I\'m testing you. You\'re failing, by the way.',
        'The voices told me to do that. QUESTION THEM, NOT ME.',
        'A ROYAL GAMBIT! You wouldn\'t understand. It\'s above your station.',
        'That move was 4D chess. 5D, even. You\'re playing 2D checkers.',
        'I\'m giving you false hope. It\'s more FUN tonight.',
        'The crown makes NO errors! That was... performance art!',
        'I MEANT to do that! The voices said it would be FUNNY!',
      ],
      draw: [
        'A DRAW? I don\'t DO draws. Someone call my lawyers!',
        'This is UNACCEPTABLE. The crown does not TIE.',
        'A draw means NEITHER of us wins. But I still win at LIFE.',
        'I\'m declaring this a ROYAL VICTORY regardless. I have that power.',
        'TIES are for COMMONERS! This is an OUTRAGE!',
      ],
    },
};
