export const magnus = {
    id: 'magnus',
    name: 'Magnus',
    rating: 2200,
    avatar: '😈',
    color: '#DC143C',
    depth: 5,
    nodes: 100000,
    blunderChance: 0,
    missedTacticsChance: 0.01,
    personality: 'Ruthless trash-talker',
    description: 'Will destroy your ego along with your position',
    playStyle: {
      aggression: 0.85,
      materialistic: 0.6,
      tactical: 0.95,
      positional: 0.9,
      drawTolerance: 0.2,
      favorsCenter: 0.8,
      kingSafety: 0.7,
      development: 0.9,
      sharp: 0.95,
    },
    quotes: {
      start: [
        "Oh, you actually clicked play? Bold. Stupid, but bold.",
        "Let's speedrun your humiliation.",
        "I'll try to make this quick. No promises though, I like watching you suffer.",
        "lol you're actually gonna do this? Okay. Your funeral.",
        "I was hoping for a challenge today. Guess I'll keep hoping.",
        "Quick question: do you even KNOW the rules? Just checking.",
        "Alright, let's see what Bronze league has to offer.",
        "I've beaten grandmasters. You're not a grandmaster. Do the math.",
      ],
      win: [
        "GG EZ. Maybe try checkers? I hear it's more your speed.",
        "Thanks for the free rating points lmaooo",
        "That wasn't even fun. You made it too easy.",
        "Skill diff. Massive skill diff.",
        "Get rekt noob. I barely even tried.",
        "lmaooo did you even practice? Ever?",
        "That's what we call a 'speedrun any%' victory.",
        "Thanks for coming to my TED talk on how to destroy you.",
        "I'd say 'good game' but I don't like lying.",
      ],
      lose: [
        "...Did you cheat? You cheated. There's no way. Reporting you.",
        "I wasn't even trying. Rematch. NOW.",
        "Lag. Definitely lag. My pieces were moving slow.",
        "Nah. Doesn't count. I was distracted. Rematch.",
        "You won because I LET you. Charity work, basically.",
        "LOL imagine thinking you actually earned that win.",
        "My cat walked on my keyboard. That's the only explanation.",
        "I'm screenshotting this so I never make this mistake again.",
      ],
      check: [
        "Check. And before you ask - no, there's no good move. I checked.",
        "Tick tock. Your king's running out of squares. And dignity.",
        "Check! What's wrong? Can't handle the pressure?",
        "Check. You know what comes next, right? You don't? LOL.",
        "Your king's running like my ex from commitment. Check.",
        "Check! I love this part. The panic in your moves is *chef's kiss*.",
        "Run, little king, run! Spoiler: you can't run forever.",
        "Check. Any last words? For your king, I mean.",
      ],
      capture: [
        "Yoink. Thanks for the free piece, noob.",
        "Imagine hanging that piece lmaooo",
        "Too easy. WAY too easy.",
        "nom nom nom. Delicious free material.",
        "That piece was asking to be taken. Loudly.",
        "I'll add this to my collection of your tears.",
        "Did you MEAN to give that away? Actually, don't answer.",
        "FREE REAL ESTATE. Thanks for the donation!",
      ],
      captured: [
        "I'm giving you hope. It's crueler that way when I crush it.",
        "Oh no! Anyway...",
        "That was bait. You fell for it. Watch.",
        "Congrats on your ONE accomplishment this game.",
        "Cute. You think you're winning now? That's adorable.",
        "Plot twist: I wanted you to take that. You played yourself.",
        "Enjoy that piece. It's the last good thing that'll happen to you.",
        "Oh wow you captured something! Want a trophy?",
      ],
      thinking: [
        "Calculating how many ways I can crush you...",
        "Trying to decide which humiliating mate to go for...",
        "Sorry, dozed off. Your position is so boring.",
        "Thinking about what I'll eat after I destroy you...",
        "Calculating... but it's not even close tbh.",
        "Should I end this now or drag it out? Decisions, decisions...",
        "Looking for the most embarrassing way to win...",
        "AFK getting snacks. This game isn't going anywhere.",
      ],
      goodMove: [
        "Okay that was actually decent. Won't save you though.",
        "Lucky move. Let's see you do it again.",
        "Huh. You CAN play chess. Who knew?",
        "Not bad. For a beginner. Are you a beginner? You play like one.",
        "Okay I'll admit that was almost smart. Almost.",
        "One good move doesn't make you a player. But nice try.",
        "Even a broken clock, am I right?",
        "Did someone help you with that? Be honest.",
      ],
      blunder: [
        "That was bait. Obviously. You think I blunder? LOL.",
        "Outplaying you so hard I can give you free pieces.",
        "I'm playing with my food. Don't get excited.",
        "I'm handicapping myself. You need ALL the help you can get.",
        "That was on purpose. Testing if you can punish it. You can't.",
        "Giving you false hope is part of my strategy. Psychological warfare.",
        "I blundered? LOL cope. I'm just built different.",
        "Oops. Anyway, watch me win regardless.",
      ],
      draw: [
        "A draw? Against YOU? Nah, this doesn't count.",
        "You got lucky. EXTREMELY lucky.",
        "A draw is basically a loss for you. I expected to WIN.",
        "Tie game? More like TRY game. For you. Because you tried. And failed to win.",
        "We're calling this a draw but we both know who the real winner is. Me.",
      ],
    },
};
