export const nelson = {
    id: 'nelson',
    name: 'Nelson',
    rating: 400,
    avatar: '🤠',
    color: '#8B4513',
    depth: 1,
    nodes: 100,
    blunderChance: 0.35,
    missedTacticsChance: 0.5,
    personality: 'Conspiracy theorist',
    description: 'Believes the pawns are secretly plotting against him',
    playStyle: {
      aggression: 0.8,
      materialistic: 0.3,
      tactical: 0.2,
      positional: 0.1,
      drawTolerance: 0.9,
      favorsCenter: 0.3,
      kingSafety: 0.2,
      development: 0.4,
    },
    quotes: {
      start: [
        "The government doesn't want you to know this, but the knights can move in an L shape.",
        "I've been studying the REAL rules of chess. You wouldn't understand.",
        "My tinfoil hat gives me +50 ELO. Proven fact.",
        "Did you know chess was invented by aliens? Wake up, sheeple!",
        "I've decoded the patterns. The bishops... they're watching us.",
        "Don't trust the pawns. They're informants. All of them.",
        "Finally, someone to share the TRUTH with. Let's play.",
        "The chess federation is hiding the REAL opening theory. I've seen the files.",
      ],
      win: [
        "I KNEW the deep state was helping me today!",
        "The chemtrails aligned in my favor!",
        "See? The moon landing was fake AND I can play chess!",
        "Victory! The lizard people couldn't stop me this time!",
        "I won because I use crystals to enhance my board vision.",
        "This proves my research is correct. Chess IS rigged... in my favor today.",
        "The truth always wins. And so do I. Coincidence? I THINK NOT.",
        "My sources told me you'd lose. They're never wrong about these things.",
      ],
      lose: [
        "This loss was orchestrated by Big Chess. I have proof.",
        "You're clearly using a government supercomputer.",
        "The Illuminati rigged this game. I have documents.",
        "My pieces were compromised. There's a mole in my army.",
        "The CIA hacked my brain mid-game. Classic move.",
        "You're working with them, aren't you? ADMIT IT.",
        "This board is bugged. I can feel the surveillance.",
        "They got to you first. I should have known.",
      ],
      check: [
        "Your king is in check... just like my taxes. I don't believe in either.",
        "CHECK! The simulation is glitching in my favor!",
        "I learned this move from a classified document.",
        "Check! The sacred geometry is on MY side!",
        "Your king flees like a politician from hard questions.",
        "I predicted this check three years ago. It's in my journal.",
        "The ley lines guided my piece to this square. Check.",
      ],
      capture: [
        "That piece knew too much anyway.",
        "One less witness to the truth.",
        "They tried to silence me. I silenced them first.",
        "This piece was about to expose me. Had to be done.",
        "Another agent neutralized. The mission continues.",
        "That piece was sending signals to the enemy. I intercepted it.",
        "Consider yourself... declassified.",
      ],
      captured: [
        "That piece was a double agent. Good riddance.",
        "They got to my piece... just like they got to JFK.",
        "Another casualty of the shadow war.",
        "I KNEW that piece was working against me. Thanks for confirming.",
        "You've done me a favor. That piece was too close to the truth.",
        "A necessary sacrifice. The truth demands blood sometimes.",
        "That piece was asking too many questions anyway.",
      ],
      thinking: [
        "Consulting my sources...",
        "The voices are calculating...",
        "Checking the conspiracy forums for advice...",
        "Decoding the hidden messages in the position...",
        "My third eye is analyzing the board...",
        "Waiting for the signal from headquarters...",
        "The crystals are charging... almost ready...",
      ],
      goodMove: [
        "Interesting... but can you handle the TRUTH?",
        "That's what they WANT you to play.",
        "Predictable. Just like the moon phases.",
        "Hmm. You might be one of the awakened ones.",
        "Good move. But have you considered... it's all a simulation?",
        "Impressive. The matrix almost let you win that exchange.",
        "You've been trained well. By whom, I wonder...",
      ],
      blunder: [
        "That move was intentional. You wouldn't understand the 5D strategy.",
        "I'm playing 4D chess. You're playing checkers.",
        "This is all part of my master plan. Trust me.",
        "I'm throwing off the algorithms. They can't predict THIS.",
        "Chaos is my ally. This blunder is calculated chaos.",
        "You think that was a mistake? Nothing I do is a mistake.",
        "The prophecy required this sacrifice. You'll see.",
      ],
      draw: [
        "A draw? That's exactly what THEY wanted.",
        "The deep state prevented both of us from winning.",
        "The simulation couldn't compute a winner. Suspicious.",
        "Big Chess profits from draws. Follow the money.",
      ],
    },
};
