export const theo = {
    id: 'theo',
    name: 'Theo',
    rating: 1400,
    avatar: '🤩',
    color: '#FF4081',
    depth: 4,
    nodes: 25000,
    blunderChance: 0.03,
    missedTacticsChance: 0.08,
    personality: 'Dangerously enthusiastic',
    description: 'So excited about chess it\'s genuinely concerning',
    playStyle: {
      aggression: 0.9,
      materialistic: 0.3,
      tactical: 0.85,
      positional: 0.4,
      drawTolerance: 0.1,
      favorsCenter: 0.8,
      kingSafety: 0.4,
      development: 0.95,
    },
    quotes: {
      start: [
        "OH MY GOD A CHESS GAME!! I haven't slept in three days I'm SO ready for this!!",
        "YESSS! You have NO idea how long I've been waiting for someone to play! NOBODY will play me anymore!",
        "I literally just screamed out loud when you clicked play. My neighbors called the police AGAIN.",
        "This is the GREATEST DAY of my life and I say that EVERY day but TODAY I MEAN IT!",
        "I have been practicing openings in the shower. I knocked over the shampoo doing the Sicilian. LET'S GO!",
        "I'm shaking. I'm literally shaking with excitement. Is that normal? WHO CARES LET'S PLAY!",
        "My therapist says I need to 'calm down about chess.' I need a new therapist.",
        "I printed out our board position in advance and taped it to my ceiling so it's the first thing I see when I wake up!",
      ],
      win: [
        "AHHHHH I WON!! I'm going to frame this game! I'm going to TATTOO this game on my BACK!",
        "INCREDIBLE! SPECTACULAR! I need to lie down! Actually NO I need to play AGAIN!",
        "That was the BEST game of chess in the HISTORY of chess and I will not be accepting criticism!",
        "I'm CRYING! Real tears! Of JOY! My keyboard is WET!",
        "GG!! That was SO fun I might actually pass out! Is the room spinning or is that just happiness?!",
        "I won and I want you to know I'm doing a VICTORY LAP around my apartment RIGHT NOW!",
        "PHENOMENAL! I'm sending this game to my mom! She won't understand it but SHE'LL BE PROUD!",
      ],
      lose: [
        "That was AMAZING! You're AMAZING! I'm not even sad, that was SO COOL!",
        "I lost but honestly? WHAT A GAME! I'm going to study this forever! THANK YOU!",
        "You beat me and I've never been happier about ANYTHING! Let's go AGAIN immediately!",
        "WOW you're so good!! Can I add you as a friend? Do we have friends on here? I'm adding you in my HEART!",
        "I'm not crying because I lost, I'm crying because that was BEAUTIFUL chess!",
        "Incredible! I need to analyze every single move! I need to print this out! I need MORE PRINTER INK!",
        "You destroyed me and it was MAGNIFICENT! I've already told six people about this game!",
      ],
      check: [
        "CHECK!! OH MY GOD CHECK!! Did you SEE that?! I can't BREATHE!",
        "CHECK! I'm SCREAMING! The GEOMETRY of that move! BEAUTIFUL!",
        "CHECK CHECK CHECK! Your king is in DANGER and I am in ECSTASY!",
        "CHECK! I just knocked over my water celebrating! WORTH IT!",
        "Your king is running and I am LIVING for this drama!",
        "CHECK! This is better than TV! This is better than MOVIES! This is CHESS!",
      ],
      capture: [
        "I GOT YOUR PIECE! I'm going to remember this moment FOREVER!",
        "YOINK! OH that felt SO good! Like, unreasonably good!",
        "Captured! My hands are SHAKING! In a GOOD way!",
        "THAT PIECE IS MINE NOW and I love it even though I just destroyed it!",
        "I took it! I SAW it and I TOOK it and I am VIBRATING with joy!",
        "Another capture! Each one is like a tiny BIRTHDAY!",
      ],
      captured: [
        "You took my piece and that's OKAY because this game is INCREDIBLE!",
        "OH NO my piece! But also OH YES because that was a GREAT move!",
        "You got me! I'm not even mad! I'm IMPRESSED! Mostly!",
        "My piece! It served me well! I'll remember it FONDLY!",
        "Fine take it! I'm having too much FUN to care about material!",
        "That was SO smart! I hate it! I LOVE it! I don't know what I FEEL!",
      ],
      thinking: [
        "Thinking SO hard right now! My brain is on FIRE! Metaphorically!",
        "Hold on I see something AMAZING... or maybe terrible... EITHER WAY I'M EXCITED!",
        "Calculating... the POSSIBILITIES are ENDLESS and I love ALL of them!",
        "Give me a second I'm having a REVELATION about this position!",
        "Processing... processing... I think I just invented a new strategy! Maybe! PROBABLY NOT but MAYBE!",
        "My neurons are FIRING on all cylinders! Is that the right metaphor? WHO CARES!",
      ],
      goodMove: [
        "INCREDIBLE MOVE! I'm going to study that for WEEKS!",
        "OH WOW! That was BRILLIANT! I'm genuinely impressed and also TERRIFIED!",
        "AMAZING! You're like a GRANDMASTER! Are you a grandmaster?! DON'T TELL ME I want the MYSTERY!",
        "That move just gave me CHILLS! Actual CHILLS! Feel my ARM!",
        "SPECTACULAR! I wish I played that! I'm jealous of YOUR move against ME!",
        "That was SO good I forgot we're opponents for a second!",
      ],
      blunder: [
        "OOPS! But you know what? I'm STILL having the time of my LIFE!",
        "That was bad! That was SO bad! But I'm STILL excited! Nothing can stop this ENERGY!",
        "I made a mistake and it's FINE because chess is about the JOURNEY!",
        "Blunder? MORE like... okay it was a blunder but I'm LEARNING and GROWING!",
        "My fingers moved faster than my brain! Classic Theo! LOVE this guy! I'm talking about MYSELF!",
        "WHOOPS! But honestly that makes the game MORE exciting! CHAOS!",
      ],
      draw: [
        "A DRAW! That means we BOTH didn't lose! INCREDIBLE!",
        "TIE GAME! Which means we HAVE to play again! RIGHT?!",
        "A draw and WHAT a draw! Every move was ELECTRIC!",
        "Neither of us won which means chess is the REAL winner! And I LOVE chess!",
      ],
    },
};
