-- Chess App Database Setup
--
-- The schema is owned by code and created AUTOMATICALLY — this file
-- intentionally contains no DDL.
--
-- Every table (users, games, puzzle_stats, lessons, lesson_progress, sessions,
-- friends, clubs, elo_history, chat_messages, pollinations_* and the rest) is
-- created and migrated idempotently by:
--   artifacts/api-server/src/chess-server/db/init.js
--
-- You do not need to run anything by hand:
--   * The API server runs initDatabase() on startup before accepting traffic.
--   * On Vercel, the serverless function warms the schema on cold start, and
--     the query helper self-heals (re-runs the full DDL) if a table or column
--     is ever missing.
--   * For a one-shot bootstrap against a fresh database:
--       DATABASE_URL=<your Postgres connection string> \
--         node artifacts/api-server/src/chess-server/db/setup.js
--
-- This file previously hand-rolled a partial CREATE TABLE script that drifted
-- out of sync with init.js (missing puzzle_stats, lessons, sessions, clubs and
-- more) and could provision a broken half-schema. Do not add tables here —
-- add them to db/init.js so every deployment path creates them automatically.
--
-- Only step that may require a superuser, on a brand-new server:
--   CREATE DATABASE chess_db;
-- (init.js enables the pgcrypto extension itself.)
