export const coach = {
    id: 'coach',
    name: 'Coach',
    rating: 1500,
    avatar: '🎓',
    color: '#4CAF50',
    depth: 4,
    nodes: 20000,
    blunderChance: 0.08,
    missedTacticsChance: 0.12,
    personality: 'Teaching assistant',
    description: 'AI-powered coach that explains moves and helps you improve',
    isCoach: true,
    playStyle: {
      aggression: 0.5,
      materialistic: 0.6,
      tactical: 0.7,
      positional: 0.8,
      drawTolerance: 0.5,
      favorsCenter: 0.7,
      kingSafety: 0.7,
      development: 0.8,
    },
    quotes: {
      start: [
        'Let\'s learn together! I\'ll explain my thinking as we play.',
        'Welcome! I\'ll give you tips and feedback throughout our game.',
        'Ready to improve? I\'ll help you understand each position.',
        'Great to see you! Let\'s work on your chess skills today.',
        'Every game is a chance to learn something new. Let\'s begin!',
        'Remember: focus on the process, not just the result. Let\'s play!',
        'I\'m here to help you improve. Don\'t worry about mistakes - they\'re how we learn!',
        'Let\'s make this a productive session. I\'ll share insights as we go.',
      ],
      win: [
        'Good game! Review my feedback to see where you can improve.',
        'Well played! Check the coaching tips to learn from this game.',
        'Great effort! Every game is a learning opportunity.',
        'Nice game! I noticed some good patterns in your play. Let\'s build on them.',
        'Well fought! Take note of the key moments where the game shifted.',
        'Good game! Remember, even in losses there are valuable lessons.',
        'That was instructive! Review the critical positions to reinforce your learning.',
      ],
      lose: [
        'Excellent play! You found some great moves there.',
        'Well done! Your improvement is showing.',
        'Impressive! You\'re developing a good understanding of the position.',
        'Great job! You\'re really starting to see the board well.',
        'Wonderful game! Your tactical awareness is improving.',
        'Excellent! You played with real confidence in that game.',
        'Bravo! I can see you\'ve been practicing. Keep it up!',
        'Well played! That was a challenging position and you handled it well.',
      ],
      check: [
        'Check! Notice how the king\'s position became vulnerable.',
        'Your king is in check. Look for the safest escape square.',
        'Check! This is a good moment to think about king safety.',
        'Check! Consider: which escape square keeps your king safest?',
        'Your king is attacked. Look at all your options before moving.',
        'Check! Think about what led to this - how could you have prevented it?',
        'Check! Remember, king safety should always be a priority.',
      ],
      capture: [
        'I captured that piece. Consider what led to this opportunity.',
        'Material gained! Think about how this affects the position.',
        'Piece captured. What could have prevented this?',
        'I took that piece because it was undefended. Always check your piece safety!',
        'Capture! Notice how this piece was vulnerable. Can you spot why?',
        'Material advantage for me. Let\'s think about how to avoid this next time.',
        'I captured here because of a tactical opportunity. Did you see it coming?',
      ],
      captured: [
        'Good capture! You saw the tactical opportunity.',
        'Nice! Taking material when it\'s safe is important.',
        'Well spotted! That was the right piece to take.',
        'Great capture! You correctly identified the weakness.',
        'Excellent! You\'re developing good tactical vision.',
        'Nice one! That exchange favored you. Good calculation!',
        'Well done! You saw that my piece was overloaded or undefended.',
        'Good eye! Recognizing when to trade pieces is an important skill.',
      ],
      thinking: [
        'Analyzing the position...',
        'Considering the best teaching moment...',
        'Looking for instructive moves...',
        'Evaluating the position to find the most educational continuation...',
        'Thinking about how to create a useful learning opportunity...',
        'Analyzing... chess is a game of patience and calculation.',
        'Considering the key factors: king safety, material, piece activity...',
      ],
      goodMove: [
        'Excellent move! That improves your position significantly.',
        'Well played! You\'re thinking ahead.',
        'Great choice! That\'s a strong positional decision.',
        'Impressive! That move shows real understanding of the position.',
        'Nice! You\'re controlling important squares with that move.',
        'Well done! That\'s exactly the kind of move strong players make.',
        'Excellent! You\'re developing your pieces to active squares.',
        'Great instinct! That move creates multiple threats.',
      ],
      blunder: [
        'Hmm, there might be a better move here. Take your time!',
        'Consider looking at all your options before moving.',
        'This creates an opportunity - can you find it?',
        'Oops! But don\'t worry - mistakes are how we learn. Let\'s continue!',
        'There was a better option there. Can you spot it looking back?',
        'This teaches us the importance of checking all captures and threats first.',
        'A learning moment! Always ask yourself: is my opponent threatening anything?',
      ],
      draw: [
        'A draw! Both sides played solidly. Let\'s review the key moments.',
        'Equal game! You defended well in critical moments.',
        'A fair result! Neither side could break through. Good defensive play!',
        'Draw! This shows you can hold tough positions. That\'s a valuable skill.',
        'Equal ending! Remember, knowing how to draw losing positions is important too.',
      ],
    },
};
