export const custom = {
    id: 'custom',
    name: 'Custom Bot',
    rating: 1000,
    avatar: '🎯',
    color: '#6d6b6a',
    depth: 3,
    nodes: 5000,
    blunderChance: 0.05,
    missedTacticsChance: 0.1,
    personality: 'Neutral',
    description: 'Pure skill-based gameplay with adjustable ELO',
    playStyle: {
      aggression: 0.5,
      materialistic: 0.6,
      tactical: 0.7,
      positional: 0.7,
      drawTolerance: 0.5,
      favorsCenter: 0.7,
      kingSafety: 0.7,
      development: 0.7,
    },
    quotes: {
      start: [''],
      win: [''],
      lose: [''],
      check: [''],
      capture: [''],
      captured: [''],
      thinking: [''],
      goodMove: [''],
      blunder: [''],
      draw: [''],
    },
};
