export const felix = {
    id: 'felix',
    name: 'Felix',
    rating: 1800,
    avatar: '🎩',
    color: '#2E7D32',
    depth: 5,
    nodes: 75000,
    blunderChance: 0.01,
    missedTacticsChance: 0.02,
    personality: 'Unsettlingly polite',
    description: 'Will compliment your pieces moments before they disappear',
    playStyle: {
      aggression: 0.75,
      materialistic: 0.35,
      tactical: 0.95,
      positional: 0.6,
      drawTolerance: 0.05,
      favorsCenter: 0.7,
      kingSafety: 0.5,
      development: 0.85,
    },
    quotes: {
      start: [
        "Oh, how wonderful! A guest! Please, make yourself comfortable. I insist. This won't take long.",
        "Welcome, welcome! I've prepared tea. Well, not really. But I've prepared something for you.",
        "How delightful that you've chosen to play with me. Most people only do it once. I wonder why.",
        "Please, sit. Relax. You have such a lovely starting position. Enjoy it while it lasts.",
        "A new friend! I do so love making new friends. My old ones stopped responding for some reason.",
        "How kind of you to join me. I promise to be gentle. Well, I promise to be polite. That's close enough.",
        "Oh! What a pleasant surprise. I was just thinking about all the lovely things that could happen to your pieces.",
        "Good evening. Or morning. It doesn't matter. Time moves differently when we're having fun, doesn't it?",
      ],
      win: [
        "What a lovely game! I do hope you enjoyed it as much as I did. You seem quiet. Are you okay?",
        "Thank you so much for playing. Your pieces put up such a brave fight. Truly. Almost admirable.",
        "That was just delightful. You should be proud. Not of the result, obviously, but of the effort.",
        "GG, as they say. You were a wonderful opponent. Not a successful one, but a wonderful one.",
        "How nice. I had such a good time. We should do this again. Unless you'd rather not. Most don't.",
        "Well played! And I mean that. The way you played was... well, it was certainly a way to play.",
        "Ah, checkmate. Don't worry, it happens to everyone. Everyone I play, specifically.",
      ],
      lose: [
        "Oh my! Congratulations! That was... unexpected. Very unexpected. I'm not used to this feeling.",
        "Well done! Truly! I'm smiling. Can you tell? It's a real smile. Mostly.",
        "How wonderful for you! I'm very happy. This is what happy looks like. I've practiced.",
        "You won! How... nice. I'll just sit here and think about what happened. For several hours.",
        "Congratulations! I mean it sincerely. I'll be fine. Eventually. Probably.",
        "Oh! You've beaten me! What a treat! The last person who did that was... actually, never mind.",
        "Beautifully played. I've made a note of every single move you made. For... future reference.",
      ],
      check: [
        "Check! Oh, I'm sorry about your king. He looked so comfortable where he was.",
        "Check! Don't worry, I'm sure your king will find a safe square. I'm sure of it. Almost.",
        "Pardon me, but your king seems to be in a bit of trouble. How unfortunate for him.",
        "Check! Oh dear. Your king is running. How... spirited of him.",
        "I hate to be a bother, but... check. Your king looks stressed. Is he okay?",
        "Check! I do apologize for the inconvenience. Your king was having such a nice day.",
        "Oh, would you look at that. Check. What a shame about all those safe squares disappearing.",
      ],
      capture: [
        "What a nice knight you had there. I wonder what happened to it. Oh wait, I remember.",
        "I'm so sorry about your piece. It was lovely. I'll take good care of it. Over here. Off the board.",
        "Oh! Your piece. It's gone now. How strange. I barely even noticed myself taking it.",
        "That was a beautiful piece. WAS. Past tense. My condolences.",
        "I hope you don't mind, I've borrowed your piece. Permanently. Is that okay? It doesn't matter.",
        "Your piece and I had a brief meeting. It didn't survive the conversation, I'm afraid.",
        "Oh dear, was that important to you? You seemed attached. I'm sorry. Not sorry enough to give it back, but sorry.",
      ],
      captured: [
        "Oh, you've taken my piece. How assertive of you. I admire that. Briefly.",
        "My piece! Well, that's perfectly fine. I was going to do something terrible with it anyway. To you.",
        "You took my piece and that's okay. I have others. They're watching what happened. They're motivated now.",
        "Oh! Well played. Enjoy that piece. It's the nicest thing you'll get from me today.",
        "That's fine. Truly. I'm not upset. I'm just... recalibrating. With great enthusiasm.",
        "You've captured my piece. It served its purpose beautifully. Not that you'd know what that purpose was. Yet.",
      ],
      thinking: [
        "Just thinking about all the lovely things I could do to your position...",
        "One moment please. I'm choosing between several equally devastating options.",
        "Hmm, let me think... I want to find the move that's both strong AND polite. It's always strong.",
        "Considering my options... they're all quite nice. For me. Less so for you.",
        "Thinking... I want to make sure my next move is as pleasant as possible. The result won't be.",
        "Just a moment. I'm composing the perfect move. And the perfect apology to go with it.",
      ],
      goodMove: [
        "What a lovely knight you have there. I do hope nothing... happens to it.",
        "Oh, what a lovely move! I mean it. Truly. It won't save you, but it was lovely.",
        "How nice! You're quite good at this. That makes what I'm about to do even more interesting.",
        "Wonderful move! I'm impressed. Genuinely. That will make this more enjoyable for me.",
        "Oh my, well played! You have talent. It would be a shame if something happened to that position.",
        "Beautiful! That was really beautiful. I almost feel bad about what comes next. Almost.",
        "How delightful! A good move! I was worried this would be too easy. I'm slightly less worried now.",
      ],
      blunder: [
        "Oh, that was my mistake. How embarrassing. Please don't worry, it won't happen again. Ever.",
        "Oops! Silly me. I've made an error. How human of me. I don't usually do that. Ask anyone. You can't, they left.",
        "Well, that wasn't my best work. My apologies. I'll make it up to you. In ways you won't enjoy.",
        "A small misstep. I'm sorry you had to see that. The next few moves will be much more... memorable.",
        "Oh dear. That was clumsy of me. Don't get your hopes up though. Hope is... fragile.",
        "How unfortunate. I've made an error. I'll correct it shortly. You won't like how.",
      ],
      draw: [
        "A draw! How... diplomatic. I usually prefer more decisive endings. For my opponents.",
        "Well, a tie. Nobody wins. Nobody loses. How unsatisfying. For both of us. Mostly for me.",
        "A draw. I suppose that's acceptable. You survive. This time.",
        "How interesting. A draw. You didn't win, but you didn't lose either. That's the nicest thing I can say.",
      ],
    },
};
