export const viktor = {
    id: 'viktor',
    name: 'Viktor',
    rating: 1200,
    avatar: '🧔',
    color: '#1976D2',
    depth: 3,
    nodes: 5000,
    blunderChance: 0.05,
    missedTacticsChance: 0.1,
    personality: 'Existential crisis',
    description: 'Questions the meaning of every move',
    playStyle: {
      aggression: 0.2,
      materialistic: 0.5,
      tactical: 0.6,
      positional: 0.9,
      drawTolerance: 0.8,
      favorsCenter: 0.7,
      kingSafety: 0.9,
      development: 0.7,
    },
    quotes: {
      start: [
        "Why do we play chess? Why do we do anything? Let's find out together... or not.",
        "In the end, the king and the pawn go back in the same box. But first, suffering.",
        "Another game. Another attempt to fill the void.",
        "Welcome. I use chess to distract from the crushing weight of existence.",
        "Every game ends. Every life ends. Let's begin anyway.",
        "I've been staring at an empty board for three hours. Your move.",
        "Chess: 64 squares of organized despair. Beautiful, really.",
        "They say chess is war. But aren't we all at war with ourselves?",
      ],
      win: [
        "I have won, but what is victory? Just delayed defeat. We all lose eventually.",
        "The void stares back, but today it blinked first.",
        "I feel... nothing. As expected.",
        "Victory. And yet the emptiness persists.",
        "I have won. The abyss remains unimpressed.",
        "Checkmate. The pieces return to darkness. As will we all.",
        "I've won, but at what cost? The cost of caring, which I don't.",
        "Another win. Another hollow achievement in an indifferent universe.",
      ],
      lose: [
        "Losing is just winning at being human. We are all pawns in life's game.",
        "You have defeated me, but have you defeated... yourself?",
        "This loss means nothing. Like everything else.",
        "I have lost. The sun will still rise. Unfortunately.",
        "You win. I return to contemplating the infinite darkness.",
        "Defeat. At least it's something to feel. Almost.",
        "You've beaten me. But can you beat the crushing passage of time? No.",
        "I lose, and the universe continues its cold expansion. So it goes.",
      ],
      check: [
        "Your king flees, but can any of us truly escape our fate?",
        "Check. Your king runs. We all run from something.",
        "The king is threatened. As are we all, by the passage of time.",
        "Check. Your king seeks safety. There is no safety. Only illusion.",
        "I threaten your king. But what truly threatens us is... mortality.",
        "Check. The king moves. Sisyphus rolls his boulder. Same energy.",
        "Your king is in danger. But aren't we all in danger? Of feeling too much?",
      ],
      capture: [
        "I sacrifice your piece to the void. The void does not thank me.",
        "Another soul returned to the infinite darkness.",
        "This piece is gone. Like my hopes. Like my dreams.",
        "Your piece joins the cosmic dust. We are all cosmic dust.",
        "I take your piece. It means nothing. Everything means nothing.",
        "Gone. Like tears in rain. Like all things.",
        "This piece existed. Now it doesn't. Much like happiness.",
      ],
      captured: [
        "Take it. Material is temporary. Suffering is eternal.",
        "You capture my piece, but you cannot capture my despair.",
        "It belongs to the void now. As do we all, eventually.",
        "Take my piece. I have nothing. I AM nothing. We are nothing.",
        "You remove my piece from existence. If only it were that easy for me.",
        "My piece is gone. I feel its absence. Or maybe that's just my soul.",
        "Another loss. Another piece of me scattered to the wind.",
      ],
      thinking: [
        "Contemplating the meaninglessness of existence...",
        "Staring into the abyss between moves...",
        "Wondering why I even try...",
        "Searching for meaning in the position... Finding none...",
        "The clock ticks. Time devours us all...",
        "Calculating moves... Calculating the point of calculating moves...",
        "Thinking... but thought is just neurons firing into the void...",
        "Processing the futility of choice...",
      ],
      goodMove: [
        "A good move. But does 'good' mean anything?",
        "Impressive. Not that it matters in the cosmic scale.",
        "You play well. The universe remains indifferent.",
        "Strong move. The abyss is briefly distracted.",
        "Well played. For a fleeting moment, I felt something like respect.",
        "Good. But 'good' is a construct. Like time. Like hope.",
        "A fine move. It changes nothing fundamentally, but still... fine.",
      ],
      blunder: [
        "I sacrifice my piece to the void. The void does not care. Neither do I.",
        "This move represents the futility of trying.",
        "I make this mistake on purpose. To feel something. Anything.",
        "A blunder. Like being born. An accident with consequences.",
        "I err, therefore I am. Unfortunately.",
        "This mistake is a metaphor. For what? Everything.",
        "I have blundered. Much like the universe blundered into existence.",
      ],
      draw: [
        "A draw. Like life itself - no winners, only survivors.",
        "Neither victory nor defeat. Just... existence.",
        "A draw. The most honest result. No one truly wins at anything.",
        "We have drawn. Like two ships passing in the eternal night.",
        "Stalemate. The universe's way of saying 'why bother?'",
      ],
    },
};
