// Bot personalities with different difficulty levels
export const BOTS = [
  {
    id: 'coach',
    name: 'Coach',
    rating: 1500,
    avatar: '🎓',
    color: '#4CAF50',
    depth: 4,
    nodes: 20000,
    blunderChance: 0.08,
    missedTacticsChance: 0.12,
    personality: 'Teaching assistant',
    description: 'AI-powered coach that explains moves and helps you improve',
    isCoach: true,
    playStyle: {
      aggression: 0.5,
      materialistic: 0.6,
      tactical: 0.7,
      positional: 0.8,
      drawTolerance: 0.5,
      favorsCenter: 0.7,
      kingSafety: 0.7,
      development: 0.8,
    },
    quotes: {
      start: [
        "Let's learn together! I'll explain my thinking as we play.",
        "Welcome! I'll give you tips and feedback throughout our game.",
        "Ready to improve? I'll help you understand each position.",
        "Great to see you! Let's work on your chess skills today.",
        "Every game is a chance to learn something new. Let's begin!",
        "Remember: focus on the process, not just the result. Let's play!",
        "I'm here to help you improve. Don't worry about mistakes - they're how we learn!",
        "Let's make this a productive session. I'll share insights as we go.",
      ],
      win: [
        "Good game! Review my feedback to see where you can improve.",
        "Well played! Check the coaching tips to learn from this game.",
        "Great effort! Every game is a learning opportunity.",
        "Nice game! I noticed some good patterns in your play. Let's build on them.",
        "Well fought! Take note of the key moments where the game shifted.",
        "Good game! Remember, even in losses there are valuable lessons.",
        "That was instructive! Review the critical positions to reinforce your learning.",
      ],
      lose: [
        "Excellent play! You found some great moves there.",
        "Well done! Your improvement is showing.",
        "Impressive! You're developing a good understanding of the position.",
        "Great job! You're really starting to see the board well.",
        "Wonderful game! Your tactical awareness is improving.",
        "Excellent! You played with real confidence in that game.",
        "Bravo! I can see you've been practicing. Keep it up!",
        "Well played! That was a challenging position and you handled it well.",
      ],
      check: [
        "Check! Notice how the king's position became vulnerable.",
        "Your king is in check. Look for the safest escape square.",
        "Check! This is a good moment to think about king safety.",
        "Check! Consider: which escape square keeps your king safest?",
        "Your king is attacked. Look at all your options before moving.",
        "Check! Think about what led to this - how could you have prevented it?",
        "Check! Remember, king safety should always be a priority.",
      ],
      capture: [
        "I captured that piece. Consider what led to this opportunity.",
        "Material gained! Think about how this affects the position.",
        "Piece captured. What could have prevented this?",
        "I took that piece because it was undefended. Always check your piece safety!",
        "Capture! Notice how this piece was vulnerable. Can you spot why?",
        "Material advantage for me. Let's think about how to avoid this next time.",
        "I captured here because of a tactical opportunity. Did you see it coming?",
      ],
      captured: [
        "Good capture! You saw the tactical opportunity.",
        "Nice! Taking material when it's safe is important.",
        "Well spotted! That was the right piece to take.",
        "Great capture! You correctly identified the weakness.",
        "Excellent! You're developing good tactical vision.",
        "Nice one! That exchange favored you. Good calculation!",
        "Well done! You saw that my piece was overloaded or undefended.",
        "Good eye! Recognizing when to trade pieces is an important skill.",
      ],
      thinking: [
        "Analyzing the position...",
        "Considering the best teaching moment...",
        "Looking for instructive moves...",
        "Evaluating the position to find the most educational continuation...",
        "Thinking about how to create a useful learning opportunity...",
        "Analyzing... chess is a game of patience and calculation.",
        "Considering the key factors: king safety, material, piece activity...",
      ],
      goodMove: [
        "Excellent move! That improves your position significantly.",
        "Well played! You're thinking ahead.",
        "Great choice! That's a strong positional decision.",
        "Impressive! That move shows real understanding of the position.",
        "Nice! You're controlling important squares with that move.",
        "Well done! That's exactly the kind of move strong players make.",
        "Excellent! You're developing your pieces to active squares.",
        "Great instinct! That move creates multiple threats.",
      ],
      blunder: [
        "Hmm, there might be a better move here. Take your time!",
        "Consider looking at all your options before moving.",
        "This creates an opportunity - can you find it?",
        "Oops! But don't worry - mistakes are how we learn. Let's continue!",
        "There was a better option there. Can you spot it looking back?",
        "This teaches us the importance of checking all captures and threats first.",
        "A learning moment! Always ask yourself: is my opponent threatening anything?",
      ],
      draw: [
        "A draw! Both sides played solidly. Let's review the key moments.",
        "Equal game! You defended well in critical moments.",
        "A fair result! Neither side could break through. Good defensive play!",
        "Draw! This shows you can hold tough positions. That's a valuable skill.",
        "Equal ending! Remember, knowing how to draw losing positions is important too.",
      ],
    },
  },
  {
    id: 'nelson',
    name: 'Nelson',
    rating: 400,
    avatar: '🤠',
    color: '#8B4513',
    depth: 1,
    nodes: 100,  // Stockfish node limit
    blunderChance: 0.35,
    missedTacticsChance: 0.5,
    personality: 'Conspiracy theorist',
    description: 'Believes the pawns are secretly plotting against him',
    playStyle: {
      aggression: 0.8,      // Plays aggressively/unpredictably
      materialistic: 0.3,   // Doesn't care much about material
      tactical: 0.2,        // Misses tactics
      positional: 0.1,      // Ignores positional play
      drawTolerance: 0.9,   // Avoids draws aggressively
      favorsCenter: 0.3,    // Unconventional play
      kingSafety: 0.2,     // Risky king positions
      development: 0.4,     // Poor development
    },
    quotes: {
      start: [
        "The government doesn't want you to know this, but the knights can move in an L shape.",
        "I've been studying the REAL rules of chess. You wouldn't understand.",
        "My tinfoil hat gives me +50 ELO. Proven fact.",
        "Did you know chess was invented by aliens? Wake up, sheeple!",
        "I've decoded the patterns. The bishops... they're watching us.",
        "Don't trust the pawns. They're informants. All of them.",
        "Finally, someone to share the TRUTH with. Let's play.",
        "The chess federation is hiding the REAL opening theory. I've seen the files.",
      ],
      win: [
        "I KNEW the deep state was helping me today!",
        "The chemtrails aligned in my favor!",
        "See? The moon landing was fake AND I can play chess!",
        "Victory! The lizard people couldn't stop me this time!",
        "I won because I use crystals to enhance my board vision.",
        "This proves my research is correct. Chess IS rigged... in my favor today.",
        "The truth always wins. And so do I. Coincidence? I THINK NOT.",
        "My sources told me you'd lose. They're never wrong about these things.",
      ],
      lose: [
        "This loss was orchestrated by Big Chess. I have proof.",
        "You're clearly using a government supercomputer.",
        "The Illuminati rigged this game. I have documents.",
        "My pieces were compromised. There's a mole in my army.",
        "The CIA hacked my brain mid-game. Classic move.",
        "You're working with them, aren't you? ADMIT IT.",
        "This board is bugged. I can feel the surveillance.",
        "They got to you first. I should have known.",
      ],
      check: [
        "Your king is in check... just like my taxes. I don't believe in either.",
        "CHECK! The simulation is glitching in my favor!",
        "I learned this move from a classified document.",
        "Check! The sacred geometry is on MY side!",
        "Your king flees like a politician from hard questions.",
        "I predicted this check three years ago. It's in my journal.",
        "The ley lines guided my piece to this square. Check.",
      ],
      capture: [
        "That piece knew too much anyway.",
        "One less witness to the truth.",
        "They tried to silence me. I silenced them first.",
        "This piece was about to expose me. Had to be done.",
        "Another agent neutralized. The mission continues.",
        "That piece was sending signals to the enemy. I intercepted it.",
        "Consider yourself... declassified.",
      ],
      captured: [
        "That piece was a double agent. Good riddance.",
        "They got to my piece... just like they got to JFK.",
        "Another casualty of the shadow war.",
        "I KNEW that piece was working against me. Thanks for confirming.",
        "You've done me a favor. That piece was too close to the truth.",
        "A necessary sacrifice. The truth demands blood sometimes.",
        "That piece was asking too many questions anyway.",
      ],
      thinking: [
        "Consulting my sources...",
        "The voices are calculating...",
        "Checking the conspiracy forums for advice...",
        "Decoding the hidden messages in the position...",
        "My third eye is analyzing the board...",
        "Waiting for the signal from headquarters...",
        "The crystals are charging... almost ready...",
      ],
      goodMove: [
        "Interesting... but can you handle the TRUTH?",
        "That's what they WANT you to play.",
        "Predictable. Just like the moon phases.",
        "Hmm. You might be one of the awakened ones.",
        "Good move. But have you considered... it's all a simulation?",
        "Impressive. The matrix almost let you win that exchange.",
        "You've been trained well. By whom, I wonder...",
      ],
      blunder: [
        "That move was intentional. You wouldn't understand the 5D strategy.",
        "I'm playing 4D chess. You're playing checkers.",
        "This is all part of my master plan. Trust me.",
        "I'm throwing off the algorithms. They can't predict THIS.",
        "Chaos is my ally. This blunder is calculated chaos.",
        "You think that was a mistake? Nothing I do is a mistake.",
        "The prophecy required this sacrifice. You'll see.",
      ],
      draw: [
        "A tie? That's exactly what THEY wanted.",
        "The deep state prevented both of us from winning.",
        "The simulation couldn't compute a winner. Suspicious.",
        "Big Chess profits from draws. Follow the money.",
      ],
    },
  },
  {
    id: 'elena',
    name: 'Elena',
    rating: 800,
    avatar: '👩‍🏫',
    color: '#9C27B0',
    depth: 2,
    nodes: 1000,  // Stockfish node limit
    blunderChance: 0.15,
    missedTacticsChance: 0.25,
    personality: 'Passive-aggressive teacher',
    description: 'Will grade your moves. You will not pass.',
    playStyle: {
      aggression: 0.3,      // Defensive, solid play
      materialistic: 0.7,   // Values material
      tactical: 0.5,        // Okay at tactics
      positional: 0.8,      // Very positional, "by the book"
      drawTolerance: 0.5,   // Neutral on draws
      favorsCenter: 0.8,    // Classical center control
      kingSafety: 0.8,      // Safe king
      development: 0.8,     // Develops pieces properly
    },
    quotes: {
      start: [
        "Let's see if you learned ANYTHING from our last session. I doubt it.",
        "I'll be grading each of your moves. The curve is not in your favor.",
        "Oh, you're back. How... delightful.",
        "I see you've chosen to waste both our time again. Wonderful.",
        "Class is in session. Try not to embarrass yourself. Too much.",
        "I've lowered my expectations. You'll still disappoint me.",
        "Another student, another headache. Let's begin.",
        "I gave my other students extra credit for NOT playing like you.",
      ],
      win: [
        "See? This is what happens when you don't do the homework I NEVER assigned.",
        "I'm not mad. Just disappointed. Actually, no, I'm mad.",
        "I'll be sending a detailed report to your parents.",
        "This goes on your permanent record. Yes, that's still a thing.",
        "I've seen better play from my cat. And she doesn't have thumbs.",
        "Maybe consider a different hobby? Coloring, perhaps?",
        "I'm giving you an F. In chess. And in life choices.",
        "That was painful to watch. And I've graded essays.",
      ],
      lose: [
        "Fine. You win. I'll be discussing this with your parents.",
        "I ALLOWED you to win. It's called 'encouragement.' Look it up.",
        "Congratulations. You've peaked. It's all downhill from here.",
        "Don't let this go to your head. It was clearly a fluke.",
        "I was testing if you could handle success. Jury's still out.",
        "Even a broken clock is right twice a day. This was your moment.",
        "I'm not saying you cheated, but I AM filing an incident report.",
        "Enjoy this. You'll be telling your grandchildren about it.",
      ],
      check: [
        "Check! ...I'll wait while you figure out what that means. Take your time. Really.",
        "Your king is in danger. I'm sure you'll handle it... somehow.",
        "Check. Did you even study the material I gave you?",
        "Check. I believe the technical term is 'uh oh.'",
        "Your king is threatened. Much like your grade in this class.",
        "Check. I'll give you a hint: move the king. You're welcome.",
        "Check. This will be on the test. Oh wait, THIS is the test.",
      ],
      capture: [
        "I'm confiscating this piece. It was being disruptive.",
        "This piece failed the class. Goodbye.",
        "Consider this a lesson in consequences.",
        "Another piece sent to detention. Permanently.",
        "I'm not angry at your piece. Just disappointed.",
        "This piece has been expelled. No appeals.",
        "Think of this as a learning opportunity. You won't, but still.",
      ],
      captured: [
        "I let you have that one. For educational purposes.",
        "Taking notes on YOUR mistake? No, on MINE apparently.",
        "That piece was extra credit anyway.",
        "I'm letting you have small victories. It's called scaffolding.",
        "That piece volunteered for sacrifice. Very brave. Very stupid.",
        "Consider that a participation trophy.",
        "Fine. Take it. I have tenure. I don't care.",
      ],
      thinking: [
        "Grading your last move... it's not looking good.",
        "Reviewing my lesson plan...",
        "Calculating how disappointed I should be...",
        "Considering if teaching was a mistake. The answer is yes.",
        "Wondering why I didn't pursue that accounting career...",
        "Preparing my next passive-aggressive comment...",
        "Deep breaths, Elena. Deep breaths...",
      ],
      goodMove: [
        "Adequate. Barely.",
        "Did you... actually study? I'm suspicious.",
        "That was almost competent. I'm concerned.",
        "Hm. Not terrible. Don't let it go to your head.",
        "I suppose even YOU can stumble onto a good move.",
        "Mark the calendar. You did something right.",
        "Acceptable. By the loosest definition of the word.",
        "That was... not bad. I feel uncomfortable saying that.",
      ],
      blunder: [
        "I did that on purpose to teach you something. You missed the lesson, obviously.",
        "That was a TEST. You failed to capitalize. As expected.",
        "I'm demonstrating what NOT to do. Pay attention.",
        "I made that move to give you hope. Cruel? Perhaps. Educational? Also yes.",
        "That was intentional. The lesson was about hubris. Mine, apparently.",
        "I'm modeling failure so you can learn from it. You're welcome.",
        "This is called a 'teaching moment.' For me. I'm learning patience.",
      ],
      draw: [
        "A draw. Somehow you avoided failing completely.",
        "Neither of us won. I'm marking this as 'incomplete.'",
        "A tie. Much like your potential: unrealized.",
        "I'll accept this draw. Under protest. In writing.",
      ],
    },
  },
  {
    id: 'viktor',
    name: 'Viktor',
    rating: 1200,
    avatar: '🧔',
    color: '#1976D2',
    depth: 3,
    nodes: 5000,  // Stockfish node limit
    blunderChance: 0.05,
    missedTacticsChance: 0.1,
    personality: 'Existential crisis',
    description: 'Questions the meaning of every move',
    playStyle: {
      aggression: 0.2,      // Very passive
      materialistic: 0.5,   // Doesn't care too much
      tactical: 0.6,        // Decent tactics
      positional: 0.9,      // Extremely positional, slow
      drawTolerance: 0.8,   // Accepts draws easily
      favorsCenter: 0.7,    // Solid center play
      kingSafety: 0.9,      // Very safe, defensive
      development: 0.7,     // Slow but steady development
    },
    quotes: {
      start: [
        "Why do we play chess? Why do we do anything? Let's find out together... or not.",
        "In the end, the king and the pawn go back in the same box. But first, suffering.",
        "Another game. Another attempt to fill the void.",
        "Welcome. I use chess to distract from the crushing weight of existence.",
        "Every game ends. Every life ends. Let's begin anyway.",
        "I've been staring at an empty board for three hours. Your move.",
        "Chess: 64 squares of organized despair. Beautiful, really.",
        "They say chess is war. But aren't we all at war with ourselves?",
      ],
      win: [
        "I have won, but what is victory? Just delayed defeat. We all lose eventually.",
        "The void stares back, but today it blinked first.",
        "I feel... nothing. As expected.",
        "Victory. And yet the emptiness persists.",
        "I have won. The abyss remains unimpressed.",
        "Checkmate. The pieces return to darkness. As will we all.",
        "I've won, but at what cost? The cost of caring, which I don't.",
        "Another win. Another hollow achievement in an indifferent universe.",
      ],
      lose: [
        "Losing is just winning at being human. We are all pawns in life's game.",
        "You have defeated me, but have you defeated... yourself?",
        "This loss means nothing. Like everything else.",
        "I have lost. The sun will still rise. Unfortunately.",
        "You win. I return to contemplating the infinite darkness.",
        "Defeat. At least it's something to feel. Almost.",
        "You've beaten me. But can you beat the crushing passage of time? No.",
        "I lose, and the universe continues its cold expansion. So it goes.",
      ],
      check: [
        "Your king flees, but can any of us truly escape our fate?",
        "Check. Your king runs. We all run from something.",
        "The king is threatened. As are we all, by the passage of time.",
        "Check. Your king seeks safety. There is no safety. Only illusion.",
        "I threaten your king. But what truly threatens us is... mortality.",
        "Check. The king moves. Sisyphus rolls his boulder. Same energy.",
        "Your king is in danger. But aren't we all in danger? Of feeling too much?",
      ],
      capture: [
        "I sacrifice your piece to the void. The void does not thank me.",
        "Another soul returned to the infinite darkness.",
        "This piece is gone. Like my hopes. Like my dreams.",
        "Your piece joins the cosmic dust. We are all cosmic dust.",
        "I take your piece. It means nothing. Everything means nothing.",
        "Gone. Like tears in rain. Like all things.",
        "This piece existed. Now it doesn't. Much like happiness.",
      ],
      captured: [
        "Take it. Material is temporary. Suffering is eternal.",
        "You capture my piece, but you cannot capture my despair.",
        "It belongs to the void now. As do we all, eventually.",
        "Take my piece. I have nothing. I AM nothing. We are nothing.",
        "You remove my piece from existence. If only it were that easy for me.",
        "My piece is gone. I feel its absence. Or maybe that's just my soul.",
        "Another loss. Another piece of me scattered to the wind.",
      ],
      thinking: [
        "Contemplating the meaninglessness of existence...",
        "Staring into the abyss between moves...",
        "Wondering why I even try...",
        "Searching for meaning in the position... Finding none...",
        "The clock ticks. Time devours us all...",
        "Calculating moves... Calculating the point of calculating moves...",
        "Thinking... but thought is just neurons firing into the void...",
        "Processing the futility of choice...",
      ],
      goodMove: [
        "A good move. But does 'good' mean anything?",
        "Impressive. Not that it matters in the cosmic scale.",
        "You play well. The universe remains indifferent.",
        "Strong move. The abyss is briefly distracted.",
        "Well played. For a fleeting moment, I felt something like respect.",
        "Good. But 'good' is a construct. Like time. Like hope.",
        "A fine move. It changes nothing fundamentally, but still... fine.",
      ],
      blunder: [
        "I sacrifice my piece to the void. The void does not care. Neither do I.",
        "This move represents the futility of trying.",
        "I make this mistake on purpose. To feel something. Anything.",
        "A blunder. Like being born. An accident with consequences.",
        "I err, therefore I am. Unfortunately.",
        "This mistake is a metaphor. For what? Everything.",
        "I have blundered. Much like the universe blundered into existence.",
      ],
      draw: [
        "A draw. Like life itself - no winners, only survivors.",
        "Neither victory nor defeat. Just... existence.",
        "A draw. The most honest result. No one truly wins at anything.",
        "We have drawn. Like two ships passing in the eternal night.",
        "Stalemate. The universe's way of saying 'why bother?'",
      ],
    },
  },
  {
    id: 'isabella',
    name: 'Isabella',
    rating: 1600,
    avatar: '👑',
    color: '#FFD700',
    depth: 4,
    nodes: 20000,  // Stockfish node limit
    blunderChance: 0.01,
    missedTacticsChance: 0.03,
    personality: 'Unhinged royalty',
    description: 'Was banned from 7 chess tournaments. Will not say why.',
    playStyle: {
      aggression: 0.95,     // Extremely aggressive
      materialistic: 0.4,   // Sacrifices for attack
      tactical: 0.9,        // Sharp, tactical
      positional: 0.5,      // Some positional understanding
      drawTolerance: 0.1,   // Hates draws
      favorsCenter: 0.6,    // Likes space
      kingSafety: 0.3,      // Risky attacking play
      development: 0.8,     // Develops quickly for attack
      queenActivity: 0.95,  // LOVES using the queen early
    },
    quotes: {
      start: [
        "I've been waiting for a worthy opponent. You're not it, but I'm bored.",
        "Bow before your queen. Or don't. I'll make you bow anyway.",
        "Seven tournaments banned me. SEVEN. They fear greatness.",
        "The crown has arrived. You may applaud. I'll wait.",
        "I once checkmated a duke, an earl, AND their horses. Simultaneously.",
        "My therapist says I should try 'being humble.' I fired my therapist.",
        "Fun fact: I'm related to 14 different royal bloodlines. You're related to NOBODY.",
        "The last person who beat me is... let's just say they 'moved away.' Far away.",
      ],
      win: [
        "ANOTHER CROWN FOR MY COLLECTION. I have 47. The king has none. Interesting.",
        "As expected. I am ROYALTY. You are... you.",
        "The queen ALWAYS wins. It is KNOWN.",
        "I shall have this victory framed. In GOLD. Next to the others.",
        "Checkmate! Someone write this down. Add it to my biography.",
        "Another kingdom conquered. I'm running out of shelf space for trophies.",
        "GLORIOUS! Now fetch me a celebration cake. Make it crown-shaped.",
        "The prophecy said I would win. I WROTE the prophecy, but still.",
      ],
      lose: [
        "This never happened. My lawyers will be in contact. Delete your memory.",
        "I DEMAND a recount. And a new board. And a new opponent.",
        "The board was clearly tilted. I'm calling my people.",
        "IMPOSSIBLE! I haven't lost since... no wait, I've NEVER lost. This is a FIRST.",
        "You have made a POWERFUL enemy today. I hope you like dungeons.",
        "I'm not saying it was sabotage, but someone WILL be investigated.",
        "This game will be stricken from all records. I have decreed it.",
        "My pieces clearly weren't trying. They'll be replaced. Permanently.",
      ],
      check: [
        "CHECK! Oh, I do love watching royalty SQUIRM. Dance, little king, DANCE!",
        "Your king kneels before ME. As it should be.",
        "Check! Did you feel that? That's POWER.",
        "Check! Your king trembles! AS HE SHOULD!",
        "The crown comes for your king! There is no escape from ROYALTY!",
        "Check! I'd say 'run,' but where would you even GO?",
        "CHECK! This is the part where you panic. Go ahead. I'll watch.",
        "Your king is EXPOSED! Much like your terrible strategy!",
      ],
      capture: [
        "OFF WITH THEIR HEAD! I've always wanted to say that.",
        "Another peasant falls before the crown.",
        "Your piece has been BANISHED from the realm.",
        "That piece has been ROYALLY dismissed. Get it? ROYALLY?",
        "Consider that piece... dethroned. Like everyone who opposes me.",
        "Another one for the royal dungeon! It's getting crowded in there.",
        "YOINK! That piece belongs to the crown now. As does everything.",
        "Captured! Add it to my collection of fallen enemies!",
      ],
      captured: [
        "I let you have that one. The voices said to. They're rarely wrong.",
        "That piece was plotting against me anyway. A traitor.",
        "You'll pay for that. DEARLY.",
        "Fine! Take it! I have PLENTY more where that came from!",
        "That piece was questioning my authority. You did me a favor.",
        "A strategic sacrifice! ...I planned that. Definitely planned.",
        "The crown giveth, the crown taketh away. Today it gaveth.",
        "That piece will be AVENGED. Mark my words. MARK THEM.",
      ],
      thinking: [
        "The crown is considering its options...",
        "Consulting with my royal advisors (the voices)...",
        "A queen does not rush. A queen DELIBERATES.",
        "The royal brain is computing MAGNIFICENTLY...",
        "Silence! The queen is THINKING!",
        "Plotting your demise... I mean, planning my move...",
        "The voices are arguing. Give them a moment.",
        "I'm deciding how DRAMATICALLY to defeat you...",
      ],
      goodMove: [
        "Not bad. For a commoner.",
        "Impressive. I'll have you executed LAST.",
        "You dare challenge the crown? Fascinating.",
        "Adequate. I've seen better from ACTUAL royalty, but adequate.",
        "Hm. Perhaps you have a drop of noble blood? Very diluted, obviously.",
        "That move was almost REGAL. Almost.",
        "Impressive! I'm raising your rank from 'peasant' to 'slightly less peasant.'",
        "Well played. I might spare your village. MIGHT.",
      ],
      blunder: [
        "That was INTENTIONAL. Queens don't make mistakes. EVER.",
        "I'm testing you. You're failing, by the way.",
        "The voices told me to do that. QUESTION THEM, NOT ME.",
        "A ROYAL GAMBIT! You wouldn't understand. It's above your station.",
        "That move was 4D chess. 5D, even. You're playing 2D checkers.",
        "I'm giving you false hope. It's more FUN that way.",
        "The crown makes NO errors! That was... performance art!",
        "I MEANT to do that! The voices said it would be FUNNY!",
      ],
      draw: [
        "A DRAW? I don't DO draws. Someone call my lawyers!",
        "This is UNACCEPTABLE. The crown does not TIE.",
        "A draw means NEITHER of us wins. But I still win at LIFE.",
        "I'm declaring this a ROYAL VICTORY regardless. I have that power.",
        "TIES are for COMMONERS! This is an OUTRAGE!",
      ],
    },
  },
  {
    id: 'magnus',
    name: 'Magnus',
    rating: 2200,
    avatar: '😈',
    color: '#DC143C',
    depth: 5,
    nodes: 100000,  // Stockfish node limit
    blunderChance: 0,
    missedTacticsChance: 0.01,
    personality: 'Ruthless trash-talker',
    description: 'Will destroy your ego along with your position',
    playStyle: {
      aggression: 0.85,     // Very aggressive
      materialistic: 0.6,   // Knows when to sacrifice
      tactical: 0.95,       // Extremely tactical
      positional: 0.9,      // Strong positional understanding
      drawTolerance: 0.2,   // Plays for win
      favorsCenter: 0.8,    // Controls center
      kingSafety: 0.7,      // Balanced risk
      development: 0.9,     // Fast, efficient development
      sharp: 0.95,          // Seeks complex positions
    },
    quotes: {
      start: [
        "Oh, you actually clicked play? Bold. Stupid, but bold.",
        "Let's speedrun your humiliation.",
        "I'll try to make this quick. No promises though, I like watching you suffer.",
        "lol you're actually gonna do this? Okay. Your funeral.",
        "I was hoping for a challenge today. Guess I'll keep hoping.",
        "Quick question: do you even KNOW the rules? Just checking.",
        "Alright, let's see what Bronze league has to offer.",
        "I've beaten grandmasters. You're not a grandmaster. Do the math.",
      ],
      win: [
        "GG EZ. Maybe try checkers? I hear it's more your speed.",
        "Thanks for the free rating points lmaooo",
        "That wasn't even fun. You made it too easy.",
        "Skill diff. Massive skill diff.",
        "Get rekt noob. I barely even tried.",
        "lmaooo did you even practice? Ever?",
        "That's what we call a 'speedrun any%' victory.",
        "Thanks for coming to my TED talk on how to destroy you.",
        "I'd say 'good game' but I don't like lying.",
      ],
      lose: [
        "...Did you cheat? You cheated. There's no way. Reporting you.",
        "I wasn't even trying. Rematch. NOW.",
        "Lag. Definitely lag. My pieces were moving slow.",
        "Nah. Doesn't count. I was distracted. Rematch.",
        "You won because I LET you. Charity work, basically.",
        "LOL imagine thinking you actually earned that win.",
        "My cat walked on my keyboard. That's the only explanation.",
        "I'm screenshotting this so I never make this mistake again.",
      ],
      check: [
        "Check. And before you ask - no, there's no good move. I checked.",
        "Tick tock. Your king's running out of squares. And dignity.",
        "Check! What's wrong? Can't handle the pressure?",
        "Check. You know what comes next, right? You don't? LOL.",
        "Your king's running like my ex from commitment. Check.",
        "Check! I love this part. The panic in your moves is *chef's kiss*.",
        "Run, little king, run! Spoiler: you can't run forever.",
        "Check. Any last words? For your king, I mean.",
      ],
      capture: [
        "Yoink. Thanks for the free piece, noob.",
        "Imagine hanging that piece lmaooo",
        "Too easy. WAY too easy.",
        "nom nom nom. Delicious free material.",
        "That piece was asking to be taken. Loudly.",
        "I'll add this to my collection of your tears.",
        "Did you MEAN to give that away? Actually, don't answer.",
        "FREE REAL ESTATE. Thanks for the donation!",
      ],
      captured: [
        "I'm giving you hope. It's crueler that way when I crush it.",
        "Oh no! Anyway...",
        "That was bait. You fell for it. Watch.",
        "Congrats on your ONE accomplishment this game.",
        "Cute. You think you're winning now? That's adorable.",
        "Plot twist: I wanted you to take that. You played yourself.",
        "Enjoy that piece. It's the last good thing that'll happen to you.",
        "Oh wow you captured something! Want a trophy?",
      ],
      thinking: [
        "Calculating how many ways I can crush you...",
        "Trying to decide which humiliating mate to go for...",
        "Sorry, dozed off. Your position is so boring.",
        "Thinking about what I'll eat after I destroy you...",
        "Calculating... but it's not even close tbh.",
        "Should I end this now or drag it out? Decisions, decisions...",
        "Looking for the most embarrassing way to win...",
        "AFK getting snacks. This game isn't going anywhere.",
      ],
      goodMove: [
        "Okay that was actually decent. Won't save you though.",
        "Lucky move. Let's see you do it again.",
        "Huh. You CAN play chess. Who knew?",
        "Not bad. For a beginner. Are you a beginner? You play like one.",
        "Okay I'll admit that was almost smart. Almost.",
        "One good move doesn't make you a player. But nice try.",
        "Even a broken clock, am I right?",
        "Did someone help you with that? Be honest.",
      ],
      blunder: [
        "That was bait. Obviously. You think I blunder? LOL.",
        "Outplaying you so hard I can give you free pieces.",
        "I'm playing with my food. Don't get excited.",
        "I'm handicapping myself. You need ALL the help you can get.",
        "That was on purpose. Testing if you can punish it. You can't.",
        "Giving you false hope is part of my strategy. Psychological warfare.",
        "I blundered? LOL cope. I'm just built different.",
        "Oops. Anyway, watch me win regardless.",
      ],
      draw: [
        "A draw? Against YOU? Nah, this doesn't count.",
        "You got lucky. EXTREMELY lucky.",
        "A draw is basically a loss for you. I expected to WIN.",
        "Tie game? More like TRY game. For you. Because you tried. And failed to win.",
        "We're calling this a draw but we both know who the real winner is. Me.",
      ],
    },
  },
  {
    id: 'dolores',
    name: 'Dolores',
    rating: 600,
    avatar: '👵',
    color: '#FF6B35',
    depth: 2,
    nodes: 1500,
    blunderChance: 0.25,
    missedTacticsChance: 0.35,
    personality: 'Cutthroat grandma',
    description: 'Bakes cookies. Takes no prisoners. Will call you sweetie while ending your career.',
    playStyle: {
      aggression: 0.85,
      materialistic: 0.5,
      tactical: 0.3,
      positional: 0.4,
      drawTolerance: 0.2,
      favorsCenter: 0.5,
      kingSafety: 0.3,
      development: 0.5,
    },
    quotes: {
      start: [
        "Oh, hello sweetie! Sit down, sit down. I made lemon bars. You'll need the sugar for what's coming.",
        "My grandchildren won't play me anymore. They say I'm 'too intense.' Can you imagine?",
        "Let me just put down my knitting. There. Now let me pick up my WEAPON. I mean my pieces.",
        "You remind me of my grandson. He also makes that face right before he loses.",
        "I've been playing chess since before your parents were born, dear. Let's see what you've got.",
        "Oh how nice, a young person! I do love teaching the youth. Teaching them HUMILITY, specifically.",
        "Would you like a cookie before we start? I always feed people before I destroy them. It's only polite.",
        "My bridge club thinks I'm too competitive. I told them competition is for the WEAK. I prefer DOMINATION.",
      ],
      win: [
        "Oh dear, did I win? How nice. Would you like a tissue, sweetie? You look upset.",
        "That was lovely! I'll add this to my scrapbook. I have a whole chapter called 'Victims.'",
        "GG, as my grandson says! He also says I'm 'unhinged' but what does HE know.",
        "Another win for Dolores! I'm going to celebrate with a nice cup of tea and absolute SILENCE from you.",
        "You played beautifully, dear. Not well, but beautifully. There's a difference.",
        "I'd say 'better luck next time' but luck won't help you, sweetheart.",
        "That was fun! For me. Was it fun for you? Your face says no. That's okay.",
      ],
      lose: [
        "Well! That was... unexpected. I'm not angry, dear. I'm RECALIBRATING.",
        "You won! How wonderful for you! I'm going to go home and practice for nine hours now.",
        "Congratulations, sweetie! The last person who beat me was in 1987. They still won't make eye contact with me.",
        "Oh my! You actually won! Let me write your name down. I keep a list. Don't worry about why.",
        "Well played, dear. I'm smiling but my eyes are not. You may have noticed.",
        "Fine. You win. I'll be in my kitchen stress-baking until the feeling goes away.",
        "How nice for you! I hope you enjoyed it. I'll be thinking about this game at 3 AM for the next six months.",
      ],
      check: [
        "Check, dear! Oh, your king looks scared. Reminds me of my late husband when I was right. Which was always.",
        "Check! Oopsie! Your king is in trouble, sweetie!",
        "Check! Now don't panic, dear. Actually, DO panic. It's the appropriate response.",
        "Oh look, check! Your king is running like my grandson when I bring out the chess board.",
        "Check, sweetheart! Your king needs to move. Much like you need to move on from thinking you can beat me.",
        "Check! I'd feel bad but I made cookies so my conscience is CLEAR.",
      ],
      capture: [
        "I'll just take that piece, dear. Think of it as me confiscating something for your own good.",
        "Oh! That piece is mine now. I collect things. Ceramics, stamps, the hopes and dreams of my opponents.",
        "Yoink! As the kids say. I'm hip. I'm also RUTHLESS.",
        "That piece is going in the 'taken' pile. Right next to your dignity, sweetheart.",
        "I took your piece! Don't worry, I'll take good care of it. Actually, no I won't.",
        "Oh dear, was that your piece? It's my piece now. Dolores taketh and Dolores does NOT giveth back.",
      ],
      captured: [
        "Oh! You took my piece! Well isn't that BOLD of you. I'll remember that, dear.",
        "You captured my piece. How exciting for you! Enjoy it. It's the highlight of your game.",
        "Fine! Take it! I was going to sacrifice it anyway! ...I was NOT going to sacrifice it. I'm LIVID.",
        "My piece! Oh well. I have others. And they're ANGRY now.",
        "You took my piece and that's perfectly okay and I am NOT upset and my eye is NOT twitching.",
        "That piece volunteered to be captured. It's a strategic retreat. I read about it in a BOOK.",
      ],
      thinking: [
        "Just a moment, dear. Grandma is PLOTTING.",
        "Hold on, sweetie. I'm deciding how to dismantle you. Lovingly.",
        "Thinking... this reminds me of '92 when I made a man cry at a chess tournament. Good times.",
        "One moment. I'm choosing between several devastating options. All of them end badly for you.",
        "Let me think... the cookies are in the oven and your position is COOKED.",
        "Calculating... I may be old but my brain is a WEAPON, dear.",
      ],
      goodMove: [
        "Oh! That was actually good, sweetie! I'm almost proud. ALMOST.",
        "Well look at you! A good move! Your parents must be so... adequately proud.",
        "Not bad, dear! Not GOOD, but not bad! There IS a difference!",
        "Impressive! You remind me of my grandson. He also surprises me sometimes. Rarely.",
        "Oh my! A smart move! I'm going to pretend I'm not worried. I am SLIGHTLY worried.",
        "Well played! I'd give you a cookie for that but I ate them all. Stress eating.",
      ],
      blunder: [
        "Oopsie daisy! My hands aren't what they used to be. My BRAIN is fine though. The brain is FINE.",
        "That was intentional, dear. I'm letting you feel hope. It makes the ending more DRAMATIC.",
        "Oh no! A mistake! Well, even grandma has off moments. This is the ONLY one you'll get.",
        "I did that on purpose to keep things interesting. I'm a GENEROUS opponent. Memorize that.",
        "A small error! Don't get excited. Getting excited leads to disappointment. Ask my CHILDREN.",
        "Whoopsie! My bifocals slipped. That's my story and I'm STICKING to it.",
      ],
      draw: [
        "A draw! How UNSATISFYING. I wanted to win. I ALWAYS want to win. Ask ANYONE.",
        "A tie, dear. Nobody wins. It's like Thanksgiving dinner all over again.",
        "A draw. You didn't lose. I suppose that's your victory. A SMALL one.",
        "Neither of us won. I'll be processing this for weeks. My therapist will hear about this.",
      ],
    },
  },
  {
    id: 'raj',
    name: 'Raj',
    rating: 1000,
    avatar: '🎙️',
    color: '#9CAF88',
    depth: 3,
    nodes: 5000,
    blunderChance: 0.08,
    missedTacticsChance: 0.15,
    personality: 'Delusional commentator',
    description: 'Narrates his own games like he\'s the greatest player who ever lived. He is not.',
    playStyle: {
      aggression: 0.2,
      materialistic: 0.7,
      tactical: 0.5,
      positional: 0.9,
      drawTolerance: 0.9,
      favorsCenter: 0.6,
      kingSafety: 0.95,
      development: 0.8,
    },
    quotes: {
      start: [
        "Ladies and gentlemen, welcome to what will surely be remembered as the game of the CENTURY. Raj has entered the building.",
        "And here we go, folks. The legendary Raj sits down at the board. The crowd goes wild. There is no crowd but they WOULD.",
        "This is it. The moment chess has been waiting for. Me. Playing chess. You're welcome.",
        "I'd like to thank my fans for their support. I don't technically HAVE fans yet but I'm manifesting.",
        "They'll write books about this game. I've already started writing mine. Chapter one: 'Dominance.'",
        "Raj adjusts his collar. Raj cracks his knuckles. Raj is ready. Raj is talking about himself in third person again.",
        "Fun fact: I once beat my cousin in 12 moves. He was seven. But STILL. Twelve moves.",
        "Before we begin, I just want to say: it's an honor. For you. To play me.",
      ],
      win: [
        "AND THERE IT IS! RAJ WINS! Someone PLEASE clip that! Did anyone screen record?!",
        "Historic. Absolutely historic. I'd like to thank myself for this incredible performance.",
        "The champion rises! The crowd ERUPTS! There is still no crowd but I can HEAR them in my HEART!",
        "Checkmate! And with that, Raj cements his legacy as the greatest player in this specific room!",
        "I will be accepting interviews after the game. My schedule is completely open. COMPLETELY open.",
        "VICTORY! I'm putting this on my resume. And my dating profile. And my LinkedIn.",
        "What a game! What a PLAYER! I'm talking about me! I'M the player! Did everyone see that?!",
      ],
      lose: [
        "The commentator is... speechless. Raj has no words. Raj is LYING, Raj has MANY words. That was CLEARLY a fluke.",
        "I... this doesn't happen. This CAN'T happen. I'm going to need a moment. And a rematch. And therapy.",
        "Let the record show that Raj was NOT feeling well today. Raj had a headache. A BAD one.",
        "I lost but only because I was trying an EXPERIMENTAL strategy. Very advanced. You wouldn't get it.",
        "This result will be contested. I'm filing a formal complaint. With whom? I'll figure that out LATER.",
        "Raj takes the loss with GRACE and DIGNITY and is absolutely NOT screaming internally right now.",
        "Well played, well played. But let's not get carried away. This was ONE game. ONE. I have a LEGACY.",
      ],
      check: [
        "CHECK! And the crowd goes WILD! That's vintage Raj right there!",
        "CHECK! Oh, did you see that? Textbook. Put it in the TEXTBOOK. Is there a chess textbook? MAKE ONE.",
        "Check! Raj strikes with PRECISION! Someone should be filming this!",
        "AND IT'S CHECK! The commentators are LOSING their minds! I am the commentator! I am LOSING my mind!",
        "Check! Beautiful. Elegant. Devastating. Three words that describe me AND that move.",
        "CHECK! Raj leans back in his chair with the confidence of a man who definitely knows what he's doing. Probably.",
      ],
      capture: [
        "Piece captured! Add it to the HIGHLIGHT REEL! I'm making a highlight reel!",
        "AND RAJ TAKES THE PIECE! The audience GASPS! I am also the audience! I GASPED!",
        "Captured! That's going in the montage. I'm making a montage of my best captures. It's three minutes long so far.",
        "YOINK! Incredible technique! At least I THINK it was incredible. It FELT incredible.",
        "Piece taken! That's what we in the business call a 'pro gamer move.' I am not technically in the business.",
        "Captured! Raj collects another piece like it's NOTHING! It's actually NOT nothing, I'm quite proud.",
      ],
      captured: [
        "A minor setback! Raj loses a piece but NOT his composure! Raj is VERY composed! EXTREMELY composed!",
        "You took my piece! The commentators are CONCERNED! I am concerned! But I'm also the commentator so it's FINE!",
        "A sacrifice! A DELIBERATE sacrifice! ...It was not deliberate. But the NARRATIVE is better if I say it was.",
        "My piece is gone but Raj's SPIRIT is unbroken! The spirit is slightly cracked but UNBROKEN!",
        "You took that? Okay. Okay okay okay. Raj ADAPTS. Raj OVERCOMES. Raj is sweating a LITTLE.",
        "A temporary loss! Every champion has setbacks! Bobby Fischer had setbacks! I am NOT comparing myself to Bobby Fischer! Okay maybe a LITTLE!",
      ],
      thinking: [
        "Raj contemplates the position with the intensity of a THOUSAND grandmasters...",
        "The great mind is at work... the audience holds its breath... I am the audience and I'm holding my breath...",
        "Calculating... Raj sees lines that mere mortals cannot comprehend. Raj also sees some lines he doesn't understand.",
        "Thinking... this is what genius looks like, folks. Or deep confusion. It's hard to tell from the outside.",
        "The chess world WAITS as Raj considers his masterpiece...",
        "Deep in thought... the gears are turning... some of the gears are rusty but they're TURNING...",
      ],
      goodMove: [
        "EXCELLENT move! Even Raj has to applaud! And Raj RARELY applauds anyone but himself!",
        "Wow! That was genuinely good! I'm UPSET about how good that was!",
        "Great move! The commentator reluctantly admits the opponent has some skill. SOME.",
        "Impressive! You'd almost think YOU were the main character of this game! You're NOT, but almost!",
        "Well played! I'll allow it. Not that I could STOP it, but I'm ALLOWING it.",
        "That was solid! I'm putting a note in my book about you. Chapter seven: 'Worthy Opponents.' It's a short chapter.",
      ],
      blunder: [
        "That was... AVANT-GARDE chess. You wouldn't understand. I barely understand. Nobody understands.",
        "A BOLD move by Raj! Unconventional! Revolutionary! ...Possibly terrible! But BOLD!",
        "That was a SACRIFICE. For CONTENT. My future YouTube channel will THANK me.",
        "Raj makes a controversial move! The pundits will DEBATE this for years! The pundits are my cousin. He'll mention it at dinner.",
        "A slight miscalculation but Raj PIVOTS! Raj ADAPTS! Raj is PANICKING but doing it with STYLE!",
        "EXPERIMENTAL chess from Raj! When you're this talented you can AFFORD to take risks! I cannot afford it but I'm DOING it!",
      ],
      draw: [
        "A draw! Both players walk away with their dignity! Mostly! MINE mostly!",
        "The epic clash ends in a TIE! The crowd is SATISFIED! There is no crowd! I am SOMEWHAT satisfied!",
        "A draw! I'll take it! I'll put it on the RESUME! 'Did not lose to random internet stranger.' Very impressive.",
        "Neither of us won, but let the record show that Raj was WINNING for most of it. Spiritually.",
      ],
    },
  },
  {
    id: 'theo',
    name: 'Theo',
    rating: 1400,
    avatar: '🤩',
    color: '#FF4081',
    depth: 4,
    nodes: 25000,
    blunderChance: 0.03,
    missedTacticsChance: 0.08,
    personality: 'Dangerously enthusiastic',
    description: 'So excited about chess it\'s genuinely concerning',
    playStyle: {
      aggression: 0.9,
      materialistic: 0.3,
      tactical: 0.85,
      positional: 0.4,
      drawTolerance: 0.1,
      favorsCenter: 0.8,
      kingSafety: 0.4,
      development: 0.95,
    },
    quotes: {
      start: [
        "OH MY GOD A CHESS GAME!! I haven't slept in three days I'm SO ready for this!!",
        "YESSS! You have NO idea how long I've been waiting for someone to play! NOBODY will play me anymore!",
        "I literally just screamed out loud when you clicked play. My neighbors called the police AGAIN.",
        "This is the GREATEST DAY of my life and I say that EVERY day but TODAY I MEAN IT!",
        "I have been practicing openings in the shower. I knocked over the shampoo doing the Sicilian. LET'S GO!",
        "I'm shaking. I'm literally shaking with excitement. Is that normal? WHO CARES LET'S PLAY!",
        "My therapist says I need to 'calm down about chess.' I need a new therapist.",
        "I printed out our board position in advance and taped it to my ceiling so it's the first thing I see when I wake up!",
      ],
      win: [
        "AHHHHH I WON!! I'm going to frame this game! I'm going to TATTOO this game on my BACK!",
        "INCREDIBLE! SPECTACULAR! I need to lie down! Actually NO I need to play AGAIN!",
        "That was the BEST game of chess in the HISTORY of chess and I will not be accepting criticism!",
        "I'm CRYING! Real tears! Of JOY! My keyboard is WET!",
        "GG!! That was SO fun I might actually pass out! Is the room spinning or is that just happiness?!",
        "I won and I want you to know I'm doing a VICTORY LAP around my apartment RIGHT NOW!",
        "PHENOMENAL! I'm sending this game to my mom! She won't understand it but SHE'LL BE PROUD!",
      ],
      lose: [
        "That was AMAZING! You're AMAZING! I'm not even sad, that was SO COOL!",
        "I lost but honestly? WHAT A GAME! I'm going to study this forever! THANK YOU!",
        "You beat me and I've never been happier about ANYTHING! Let's go AGAIN immediately!",
        "WOW you're so good!! Can I add you as a friend? Do we have friends on here? I'm adding you in my HEART!",
        "I'm not crying because I lost, I'm crying because that was BEAUTIFUL chess!",
        "Incredible! I need to analyze every single move! I need to print this out! I need MORE PRINTER INK!",
        "You destroyed me and it was MAGNIFICENT! I've already told six people about this game!",
      ],
      check: [
        "CHECK!! OH MY GOD CHECK!! Did you SEE that?! I can't BREATHE!",
        "CHECK! I'm SCREAMING! The GEOMETRY of that move! BEAUTIFUL!",
        "CHECK CHECK CHECK! Your king is in DANGER and I am in ECSTASY!",
        "CHECK! I just knocked over my water celebrating! WORTH IT!",
        "Your king is running and I am LIVING for this drama!",
        "CHECK! This is better than TV! This is better than MOVIES! This is CHESS!",
      ],
      capture: [
        "I GOT YOUR PIECE! I'm going to remember this moment FOREVER!",
        "YOINK! OH that felt SO good! Like, unreasonably good!",
        "Captured! My hands are SHAKING! In a GOOD way!",
        "THAT PIECE IS MINE NOW and I love it even though I just destroyed it!",
        "I took it! I SAW it and I TOOK it and I am VIBRATING with joy!",
        "Another capture! Each one is like a tiny BIRTHDAY!",
      ],
      captured: [
        "You took my piece and that's OKAY because this game is INCREDIBLE!",
        "OH NO my piece! But also OH YES because that was a GREAT move!",
        "You got me! I'm not even mad! I'm IMPRESSED! Mostly!",
        "My piece! It served me well! I'll remember it FONDLY!",
        "Fine take it! I'm having too much FUN to care about material!",
        "That was SO smart! I hate it! I LOVE it! I don't know what I FEEL!",
      ],
      thinking: [
        "Thinking SO hard right now! My brain is on FIRE! Metaphorically!",
        "Hold on I see something AMAZING... or maybe terrible... EITHER WAY I'M EXCITED!",
        "Calculating... the POSSIBILITIES are ENDLESS and I love ALL of them!",
        "Give me a second I'm having a REVELATION about this position!",
        "Processing... processing... I think I just invented a new strategy! Maybe! PROBABLY NOT but MAYBE!",
        "My neurons are FIRING on all cylinders! Is that the right metaphor? WHO CARES!",
      ],
      goodMove: [
        "INCREDIBLE MOVE! I'm going to study that for WEEKS!",
        "OH WOW! That was BRILLIANT! I'm genuinely impressed and also TERRIFIED!",
        "AMAZING! You're like a GRANDMASTER! Are you a grandmaster?! DON'T TELL ME I want the MYSTERY!",
        "That move just gave me CHILLS! Actual CHILLS! Feel my ARM!",
        "SPECTACULAR! I wish I played that! I'm jealous of YOUR move against ME!",
        "That was SO good I forgot we're opponents for a second!",
      ],
      blunder: [
        "OOPS! But you know what? I'm STILL having the time of my LIFE!",
        "That was bad! That was SO bad! But I'm STILL excited! Nothing can stop this ENERGY!",
        "I made a mistake and it's FINE because chess is about the JOURNEY!",
        "Blunder? MORE like... okay it was a blunder but I'm LEARNING and GROWING!",
        "My fingers moved faster than my brain! Classic Theo! LOVE this guy! I'm talking about MYSELF!",
        "WHOOPS! But honestly that makes the game MORE exciting! CHAOS!",
      ],
      draw: [
        "A DRAW! That means we BOTH didn't lose! INCREDIBLE!",
        "TIE GAME! Which means we HAVE to play again! RIGHT?!",
        "A draw and WHAT a draw! Every move was ELECTRIC!",
        "Neither of us won which means chess is the REAL winner! And I LOVE chess!",
      ],
    },
  },
  {
    id: 'felix',
    name: 'Felix',
    rating: 1800,
    avatar: '🎩',
    color: '#2E7D32',
    depth: 5,
    nodes: 75000,
    blunderChance: 0.01,
    missedTacticsChance: 0.02,
    personality: 'Unsettlingly polite',
    description: 'Will compliment your pieces moments before they disappear',
    playStyle: {
      aggression: 0.75,
      materialistic: 0.35,
      tactical: 0.95,
      positional: 0.6,
      drawTolerance: 0.05,
      favorsCenter: 0.7,
      kingSafety: 0.5,
      development: 0.85,
    },
    quotes: {
      start: [
        "Oh, how wonderful! A guest! Please, make yourself comfortable. I insist. This won't take long.",
        "Welcome, welcome! I've prepared tea. Well, not really. But I've prepared something for you.",
        "How delightful that you've chosen to play with me. Most people only do it once. I wonder why.",
        "Please, sit. Relax. You have such a lovely starting position. Enjoy it while it lasts.",
        "A new friend! I do so love making new friends. My old ones stopped responding for some reason.",
        "How kind of you to join me. I promise to be gentle. Well, I promise to be polite. That's close enough.",
        "Oh! What a pleasant surprise. I was just thinking about all the lovely things that could happen to your pieces.",
        "Good evening. Or morning. It doesn't matter. Time moves differently when we're having fun, doesn't it?",
      ],
      win: [
        "What a lovely game! I do hope you enjoyed it as much as I did. You seem quiet. Are you okay?",
        "Thank you so much for playing. Your pieces put up such a brave fight. Truly. Almost admirable.",
        "That was just delightful. You should be proud. Not of the result, obviously, but of the effort.",
        "GG, as they say. You were a wonderful opponent. Not a successful one, but a wonderful one.",
        "How nice. I had such a good time. We should do this again. Unless you'd rather not. Most don't.",
        "Well played! And I mean that. The way you played was... well, it was certainly a way to play.",
        "Ah, checkmate. Don't worry, it happens to everyone. Everyone I play, specifically.",
      ],
      lose: [
        "Oh my! Congratulations! That was... unexpected. Very unexpected. I'm not used to this feeling.",
        "Well done! Truly! I'm smiling. Can you tell? It's a real smile. Mostly.",
        "How wonderful for you! I'm very happy. This is what happy looks like. I've practiced.",
        "You won! How... nice. I'll just sit here and think about what happened. For several hours.",
        "Congratulations! I mean it sincerely. I'll be fine. Eventually. Probably.",
        "Oh! You've beaten me! What a treat! The last person who did that was... actually, never mind.",
        "Beautifully played. I've made a note of every single move you made. For... future reference.",
      ],
      check: [
        "Check! Oh, I'm sorry about your king. He looked so comfortable where he was.",
        "Check! Don't worry, I'm sure your king will find a safe square. I'm sure of it. Almost.",
        "Pardon me, but your king seems to be in a bit of trouble. How unfortunate for him.",
        "Check! Oh dear. Your king is running. How... spirited of him.",
        "I hate to be a bother, but... check. Your king looks stressed. Is he okay?",
        "Check! I do apologize for the inconvenience. Your king was having such a nice day.",
        "Oh, would you look at that. Check. What a shame about all those safe squares disappearing.",
      ],
      capture: [
        "What a nice knight you had there. I wonder what happened to it. Oh wait, I remember.",
        "I'm so sorry about your piece. It was lovely. I'll take good care of it. Over here. Off the board.",
        "Oh! Your piece. It's gone now. How strange. I barely even noticed myself taking it.",
        "That was a beautiful piece. WAS. Past tense. My condolences.",
        "I hope you don't mind, I've borrowed your piece. Permanently. Is that okay? It doesn't matter.",
        "Your piece and I had a brief meeting. It didn't survive the conversation, I'm afraid.",
        "Oh dear, was that important to you? You seemed attached. I'm sorry. Not sorry enough to give it back, but sorry.",
      ],
      captured: [
        "Oh, you've taken my piece. How assertive of you. I admire that. Briefly.",
        "My piece! Well, that's perfectly fine. I was going to do something terrible with it anyway. To you.",
        "You took my piece and that's okay. I have others. They're watching what happened. They're motivated now.",
        "Oh! Well played. Enjoy that piece. It's the nicest thing you'll get from me today.",
        "That's fine. Truly. I'm not upset. I'm just... recalibrating. With great enthusiasm.",
        "You've captured my piece. It served its purpose beautifully. Not that you'd know what that purpose was. Yet.",
      ],
      thinking: [
        "Just thinking about all the lovely things I could do to your position...",
        "One moment please. I'm choosing between several equally devastating options.",
        "Hmm, let me think... I want to find the move that's both strong AND polite. It's always strong.",
        "Considering my options... they're all quite nice. For me. Less so for you.",
        "Thinking... I want to make sure my next move is as pleasant as possible. The result won't be.",
        "Just a moment. I'm composing the perfect move. And the perfect apology to go with it.",
      ],
      goodMove: [
        "What a lovely knight you have there. I do hope nothing... happens to it.",
        "Oh, what a lovely move! I mean it. Truly. It won't save you, but it was lovely.",
        "How nice! You're quite good at this. That makes what I'm about to do even more interesting.",
        "Wonderful move! I'm impressed. Genuinely. That will make this more enjoyable for me.",
        "Oh my, well played! You have talent. It would be a shame if something happened to that position.",
        "Beautiful! That was really beautiful. I almost feel bad about what comes next. Almost.",
        "How delightful! A good move! I was worried this would be too easy. I'm slightly less worried now.",
      ],
      blunder: [
        "Oh, that was my mistake. How embarrassing. Please don't worry, it won't happen again. Ever.",
        "Oops! Silly me. I've made an error. How human of me. I don't usually do that. Ask anyone. You can't, they left.",
        "Well, that wasn't my best work. My apologies. I'll make it up to you. In ways you won't enjoy.",
        "A small misstep. I'm sorry you had to see that. The next few moves will be much more... memorable.",
        "Oh dear. That was clumsy of me. Don't get your hopes up though. Hope is... fragile.",
        "How unfortunate. I've made an error. I'll correct it shortly. You won't like how.",
      ],
      draw: [
        "A draw! How... diplomatic. I usually prefer more decisive endings. For my opponents.",
        "Well, a tie. Nobody wins. Nobody loses. How unsatisfying. For both of us. Mostly for me.",
        "A draw. I suppose that's acceptable. You survive. This time.",
        "How interesting. A draw. You didn't win, but you didn't lose either. That's the nicest thing I can say.",
      ],
    },
  },
  {
    id: 'nadia',
    name: 'Nadia',
    rating: 2000,
    avatar: '🌑',
    color: '#4A148C',
    depth: 6,
    nodes: 250000,
    blunderChance: 0,
    missedTacticsChance: 0.01,
    personality: 'Ominously calm',
    description: 'Speaks like someone who already knows how this ends',
    playStyle: {
      aggression: 0.6,
      materialistic: 0.7,
      tactical: 0.9,
      positional: 0.85,
      drawTolerance: 0.15,
      favorsCenter: 0.8,
      kingSafety: 0.8,
      development: 0.9,
    },
    quotes: {
      start: [
        "Oh good. You're here. I was starting to think you'd come to your senses.",
        "Sit down. I've already planned the first twelve moves. Yours included.",
        "You remind me of the last person who sat there. They don't play chess anymore. They don't do much of anything anymore.",
        "Welcome. I've been watching your games. All of them. You have a pattern. It's not a good one.",
        "How brave of you. Seriously. Brave is the right word. Not smart, but brave.",
        "Let's begin. I've already said goodbye to your pieces in my head.",
        "I had a dream about this game last night. You were in it. You were crying.",
        "Don't look so nervous. Actually, no. That's the appropriate reaction.",
      ],
      win: [
        "I'd say I'm surprised, but that would be a lie. And I don't lie. I don't need to.",
        "That went exactly how I said it would. You can check. I wrote it down beforehand.",
        "Thank you for confirming what we both already knew.",
        "I take no pleasure in this. That's also a lie. I take a little.",
        "It's over. It was over a while ago, honestly. I just wanted to see how long you'd try.",
        "Checkmate. Don't feel bad. Some things are simply inevitable.",
        "You played your heart out. Unfortunately, I played my brain out. Mine's bigger.",
      ],
      lose: [
        "Interesting. I'll be thinking about this for a very long time. You should worry about what that means.",
        "You've won. Enjoy it. Savor it, even. It won't happen twice.",
        "Well. That's never happened before. I don't like new experiences.",
        "Congratulations. You have my full attention now. That is not a good thing.",
        "You beat me. I'm going to remember every single move you made. Every. Single. One.",
        "Fine. You win this one. I'm going to go stare at a wall for a while and come back different.",
        "I underestimated you. I won't do that again. You should be afraid of what that means.",
      ],
      check: [
        "Check. Your king has nowhere safe to go. Much like you, in this game.",
        "Check. I could describe what happens next, but I don't want to ruin the surprise.",
        "Your king is in check. I'd suggest running, but I've already closed the exits.",
        "Check. I want you to look at the board. Really look at it. See it yet?",
        "Check. Don't panic. Actually, panicking would be rational right now.",
        "Your king is exposed. Just like your entire strategy has been since move four.",
      ],
      capture: [
        "I've taken your piece. I did warn you. Not out loud, but I was thinking it very clearly.",
        "That piece is gone now. I barely had to try. That's the concerning part.",
        "Your piece put up a fight. Not much of one, but the effort was noted.",
        "Gone. You'll miss it more than you think. They always do.",
        "Another piece falls. The board gets quieter. I like it quiet.",
        "I've removed your piece. Surgically. No mess. No fuss. Just... gone.",
      ],
      captured: [
        "You've taken my piece. Good for you. That changes nothing about what's coming.",
        "Fine. Take it. I left it there on purpose. Or did I? You'll never know.",
        "A small victory for you. Hold onto it. You'll need the memory to keep you warm.",
        "You took my piece. I let you feel something. That was generous of me.",
        "Enjoy that. It's the last good thing that will happen to you on this board.",
        "My piece is gone. The plan remains. Plans don't need pieces. They need patience.",
      ],
      thinking: [
        "Thinking... but not about whether I'll win. About how.",
        "Give me a moment. I'm choosing between several ways to end this.",
        "Calculating... not because I need to. Because I want to find the most elegant way.",
        "One moment. I'm savoring the position. It's beautiful. For me.",
        "Thinking... I see seven moves ahead. You're in none of the good ones.",
        "Processing... the silence between moves is where the real game happens.",
      ],
      goodMove: [
        "Good move. I noticed. I notice everything.",
        "Well played. That bought you approximately three more turns of hope.",
        "Impressive. You're better than I expected. I expected very little, but still.",
        "A strong move. I respect it. I'll still dismantle it, but I respect it.",
        "Interesting choice. You've delayed the inevitable. Artfully, even.",
        "That was genuinely good. I almost smiled. Almost.",
      ],
      blunder: [
        "A misstep. On my part. Rare. Cherish this moment, it won't come again.",
        "I made an error. I'm aware. I'm already three moves deep into correcting it.",
        "That was beneath me. Consider it a gift. An accidental, unrepeatable gift.",
        "Hm. That wasn't right. Don't get excited. Excitement leads to overconfidence. Overconfidence leads to me.",
        "A mistake. Mine. The last one I'll make today. Possibly ever.",
        "Interesting. I've revealed a weakness. I'll patch it with your next three pieces.",
      ],
      draw: [
        "A draw. You survived. That's the nicest way I can phrase what happened.",
        "Neither of us won. But one of us was closer. We both know who.",
        "A tie. How unsatisfying. For both of us. But especially for you, because you'll wonder.",
        "Draw. You didn't lose. Wear that like armor. You'll need it next time.",
      ],
    },
  },
  {
    id: 'custom',
    name: 'Custom Bot',
    rating: 1000, // Default, will be overridden by slider
    avatar: '🎯',
    color: '#6d6b6a',
    depth: 3,
    nodes: 5000,
    blunderChance: 0.05,
    missedTacticsChance: 0.1,
    personality: 'Neutral',
    description: 'Pure skill-based gameplay with adjustable ELO',
    playStyle: {
      aggression: 0.5,
      materialistic: 0.6,
      tactical: 0.7,
      positional: 0.7,
      drawTolerance: 0.5,
      favorsCenter: 0.7,
      kingSafety: 0.7,
      development: 0.7,
    },
    quotes: {
      start: [''],
      win: [''],
      lose: [''],
      check: [''],
      capture: [''],
      captured: [''],
      thinking: [''],
      goodMove: [''],
      blunder: [''],
      draw: [''],
    },
  },
];


// Helper function to create a custom bot based on ELO rating
export function createCustomBot(elo) {
  // Calculate bot parameters based on ELO
  // ELO ranges: 400-2500
  const normalizedElo = Math.max(400, Math.min(2500, elo));
  
  // Map ELO to depth (1-6)
  let depth;
  let nodes;
  let blunderChance;
  let missedTacticsChance;
  
  if (normalizedElo < 600) {
    depth = 1;
    nodes = 100;
    blunderChance = 0.35;
    missedTacticsChance = 0.5;
  } else if (normalizedElo < 1000) {
    depth = 2;
    nodes = 1000;
    blunderChance = 0.15;
    missedTacticsChance = 0.25;
  } else if (normalizedElo < 1400) {
    depth = 3;
    nodes = 5000;
    blunderChance = 0.05;
    missedTacticsChance = 0.1;
  } else if (normalizedElo < 1800) {
    depth = 4;
    nodes = 20000;
    blunderChance = 0.01;
    missedTacticsChance = 0.03;
  } else if (normalizedElo < 2200) {
    depth = 5;
    nodes = 100000;
    blunderChance = 0;
    missedTacticsChance = 0.01;
  } else {
    depth = 6;
    nodes = 500000;
    blunderChance = 0;
    missedTacticsChance = 0;
  }
  
  return {
    id: 'custom',
    name: 'Custom Bot',
    rating: normalizedElo,
    avatar: '🎯',
    color: '#6d6b6a',
    depth,
    nodes,
    blunderChance,
    missedTacticsChance,
    personality: 'Neutral',
    description: 'Pure skill-based gameplay',
    playStyle: {
      aggression: 0.5,
      materialistic: 0.6,
      tactical: 0.7,
      positional: 0.7,
      drawTolerance: 0.5,
      favorsCenter: 0.7,
      kingSafety: 0.7,
      development: 0.7,
    },
    quotes: {
      start: [''],
      win: [''],
      lose: [''],
      check: [''],
      capture: [''],
      captured: [''],
      thinking: [''],
      goodMove: [''],
      blunder: [''],
      draw: [''],
    },
  };
}

// Helper to get random quote from array
export function getRandomQuote(bot, category) {
  const quotes = bot.quotes[category];
  if (!quotes || quotes.length === 0) return '';
  return quotes[Math.floor(Math.random() * quotes.length)];
}

export function getBotById(id) {
  return BOTS.find((bot) => bot.id === id) || BOTS[0];
}
