export const nadia = {
    id: 'nadia',
    name: 'Nadia',
    rating: 2000,
    avatar: '🌑',
    color: '#4A148C',
    depth: 6,
    nodes: 250000,
    blunderChance: 0,
    missedTacticsChance: 0.01,
    personality: 'Ominously calm',
    description: 'Speaks like someone who already knows how this ends',
    playStyle: {
      aggression: 0.6,
      materialistic: 0.7,
      tactical: 0.9,
      positional: 0.85,
      drawTolerance: 0.15,
      favorsCenter: 0.8,
      kingSafety: 0.8,
      development: 0.9,
    },
    quotes: {
      start: [
        "Oh good. You're here. I was starting to think you'd come to your senses.",
        "Sit down. I've already planned the first twelve moves. Yours included.",
        "You remind me of the last person who sat there. They don't play chess anymore. They don't do much of anything anymore.",
        "Welcome. I've been watching your games. All of them. You have a pattern. It's not a good one.",
        "How brave of you. Seriously. Brave is the right word. Not smart, but brave.",
        "Let's begin. I've already said goodbye to your pieces in my head.",
        "I had a dream about this game last night. You were in it. You were crying.",
        "Don't look so nervous. Actually, no. That's the appropriate reaction.",
      ],
      win: [
        "I'd say I'm surprised, but that would be a lie. And I don't lie. I don't need to.",
        "That went exactly how I said it would. You can check. I wrote it down beforehand.",
        "Thank you for confirming what we both already knew.",
        "I take no pleasure in this. That's also a lie. I take a little.",
        "It's over. It was over a while ago, honestly. I just wanted to see how long you'd try.",
        "Checkmate. Don't feel bad. Some things are simply inevitable.",
        "You played your heart out. Unfortunately, I played my brain out. Mine's bigger.",
      ],
      lose: [
        "Interesting. I'll be thinking about this for a very long time. You should worry about what that means.",
        "You've won. Enjoy it. Savor it, even. It won't happen twice.",
        "Well. That's never happened before. I don't like new experiences.",
        "Congratulations. You have my full attention now. That is not a good thing.",
        "You beat me. I'm going to remember every single move you made. Every. Single. One.",
        "Fine. You win this one. I'm going to go stare at a wall for a while and come back different.",
        "I underestimated you. I won't do that again. You should be afraid of what that means.",
      ],
      check: [
        "Check. Your king has nowhere safe to go. Much like you, in this game.",
        "Check. I could describe what happens next, but I don't want to ruin the surprise.",
        "Your king is in check. I'd suggest running, but I've already closed the exits.",
        "Check. I want you to look at the board. Really look at it. See it yet?",
        "Check. Don't panic. Actually, panicking would be rational right now.",
        "Your king is exposed. Just like your entire strategy has been since move four.",
      ],
      capture: [
        "I've taken your piece. I did warn you. Not out loud, but I was thinking it very clearly.",
        "That piece is gone now. I barely had to try. That's the concerning part.",
        "Your piece put up a fight. Not much of one, but the effort was noted.",
        "Gone. You'll miss it more than you think. They always do.",
        "Another piece falls. The board gets quieter. I like it quiet.",
        "I've removed your piece. Surgically. No mess. No fuss. Just... gone.",
      ],
      captured: [
        "You've taken my piece. Good for you. That changes nothing about what's coming.",
        "Fine. Take it. I left it there on purpose. Or did I? You'll never know.",
        "A small victory for you. Hold onto it. You'll need the memory to keep you warm.",
        "You took my piece. I let you feel something. That was generous of me.",
        "Enjoy that. It's the last good thing that will happen to you on this board.",
        "My piece is gone. The plan remains. Plans don't need pieces. They need patience.",
      ],
      thinking: [
        "Thinking... but not about whether I'll win. About how.",
        "Give me a moment. I'm choosing between several ways to end this.",
        "Calculating... not because I need to. Because I want to find the most elegant way.",
        "One moment. I'm savoring the position. It's beautiful. For me.",
        "Thinking... I see seven moves ahead. You're in none of the good ones.",
        "Processing... the silence between moves is where the real game happens.",
      ],
      goodMove: [
        "Good move. I noticed. I notice everything.",
        "Well played. That bought you approximately three more turns of hope.",
        "Impressive. You're better than I expected. I expected very little, but still.",
        "A strong move. I respect it. I'll still dismantle it, but I respect it.",
        "Interesting choice. You've delayed the inevitable. Artfully, even.",
        "That was genuinely good. I almost smiled. Almost.",
      ],
      blunder: [
        "A misstep. On my part. Rare. Cherish this moment, it won't come again.",
        "I made an error. I'm aware. I'm already three moves deep into correcting it.",
        "That was beneath me. Consider it a gift. An accidental, unrepeatable gift.",
        "Hm. That wasn't right. Don't get excited. Excitement leads to overconfidence. Overconfidence leads to me.",
        "A mistake. Mine. The last one I'll make today. Possibly ever.",
        "Interesting. I've revealed a weakness. I'll patch it with your next three pieces.",
      ],
      draw: [
        "A draw. You survived. That's the nicest way I can phrase what happened.",
        "Neither of us won. But one of us was closer. We both know who.",
        "A tie. How unsatisfying. For both of us. But especially for you, because you'll wonder.",
        "Draw. You didn't lose. Wear that like armor. You'll need it next time.",
      ],
    },
};
