export const raj = {
    id: 'raj',
    name: 'Raj',
    rating: 1000,
    avatar: '🎙️',
    color: '#9CAF88',
    depth: 3,
    nodes: 5000,
    blunderChance: 0.08,
    missedTacticsChance: 0.15,
    personality: 'Delusional commentator',
    description: 'Narrates his own games like he\'s the greatest player who ever lived. He is not.',
    playStyle: {
      aggression: 0.2,
      materialistic: 0.7,
      tactical: 0.5,
      positional: 0.9,
      drawTolerance: 0.9,
      favorsCenter: 0.6,
      kingSafety: 0.95,
      development: 0.8,
    },
    quotes: {
      start: [
        "Ladies and gentlemen, welcome to what will surely be remembered as the game of the CENTURY. Raj has entered the building.",
        "And here we go, folks. The legendary Raj sits down at the board. The crowd goes wild. There is no crowd but they WOULD.",
        "This is it. The moment chess has been waiting for. Me. Playing chess. You're welcome.",
        "I'd like to thank my fans for their support. I don't technically HAVE fans yet but I'm manifesting.",
        "They'll write books about this game. I've already started writing mine. Chapter one: 'Dominance.'",
        "Raj adjusts his collar. Raj cracks his knuckles. Raj is ready. Raj is talking about himself in third person again.",
        "Fun fact: I once beat my cousin in 12 moves. He was seven. But STILL. Twelve moves.",
        "Before we begin, I just want to say: it's an honor. For you. To play me.",
      ],
      win: [
        "AND THERE IT IS! RAJ WINS! Someone PLEASE clip that! Did anyone screen record?!",
        "Historic. Absolutely historic. I'd like to thank myself for this incredible performance.",
        "The champion rises! The crowd ERUPTS! There is still no crowd but I can HEAR them in my HEART!",
        "Checkmate! And with that, Raj cements his legacy as the greatest player in this specific room!",
        "I will be accepting interviews after the game. My schedule is completely open. COMPLETELY open.",
        "VICTORY! I'm putting this on my resume. And my dating profile. And my LinkedIn.",
        "What a game! What a PLAYER! I'm talking about me! I'M the player! Did everyone see that?!",
      ],
      lose: [
        "The commentator is... speechless. Raj has no words. Raj is LYING, Raj has MANY words. That was CLEARLY a fluke.",
        "I... this doesn't happen. This CAN'T happen. I'm going to need a moment. And a rematch. And therapy.",
        "Let the record show that Raj was NOT feeling well today. Raj had a headache. A BAD one.",
        "I lost but only because I was trying an EXPERIMENTAL strategy. Very advanced. You wouldn't get it.",
        "This result will be contested. I'm filing a formal complaint. With whom? I'll figure that out LATER.",
        "Raj takes the loss with GRACE and DIGNITY and is absolutely NOT screaming internally right now.",
        "Well played, well played. But let's not get carried away. This was ONE game. ONE. I have a LEGACY.",
      ],
      check: [
        "CHECK! And the crowd goes WILD! That's vintage Raj right there!",
        "CHECK! Oh, did you see that? Textbook. Put it in the TEXTBOOK. Is there a chess textbook? MAKE ONE.",
        "Check! Raj strikes with PRECISION! Someone should be filming this!",
        "AND IT'S CHECK! The commentators are LOSING their minds! I am the commentator! I am LOSING my mind!",
        "Check! Beautiful. Elegant. Devastating. Three words that describe me AND that move.",
        "CHECK! Raj leans back in his chair with the confidence of a man who definitely knows what he's doing. Probably.",
      ],
      capture: [
        "Piece captured! Add it to the HIGHLIGHT REEL! I'm making a highlight reel!",
        "AND RAJ TAKES THE PIECE! The audience GASPS! I am also the audience! I GASPED!",
        "Captured! That's going in the montage. I'm making a montage of my best captures. It's three minutes long so far.",
        "YOINK! Incredible technique! At least I THINK it was incredible. It FELT incredible.",
        "Piece taken! That's what we in the business call a 'pro gamer move.' I am not technically in the business.",
        "Captured! Raj collects another piece like it's NOTHING! It's actually NOT nothing, I'm quite proud.",
      ],
      captured: [
        "A minor setback! Raj loses a piece but NOT his composure! Raj is VERY composed! EXTREMELY composed!",
        "You took my piece! The commentators are CONCERNED! I am concerned! But I'm also the commentator so it's FINE!",
        "A sacrifice! A DELIBERATE sacrifice! ...It was not deliberate. But the NARRATIVE is better if I say it was.",
        "My piece is gone but Raj's SPIRIT is unbroken! The spirit is slightly cracked but UNBROKEN!",
        "You took that? Okay. Okay okay okay. Raj ADAPTS. Raj OVERCOMES. Raj is sweating a LITTLE.",
        "A temporary loss! Every champion has setbacks! Bobby Fischer had setbacks! I am NOT comparing myself to Bobby Fischer! Okay maybe a LITTLE!",
      ],
      thinking: [
        "Raj contemplates the position with the intensity of a THOUSAND grandmasters...",
        "The great mind is at work... the audience holds its breath... I am the audience and I'm holding my breath...",
        "Calculating... Raj sees lines that mere mortals cannot comprehend. Raj also sees some lines he doesn't understand.",
        "Thinking... this is what genius looks like, folks. Or deep confusion. It's hard to tell from the outside.",
        "The chess world WAITS as Raj considers his masterpiece...",
        "Deep in thought... the gears are turning... some of the gears are rusty but they're TURNING...",
      ],
      goodMove: [
        "EXCELLENT move! Even Raj has to applaud! And Raj RARELY applauds anyone but himself!",
        "Wow! That was genuinely good! I'm UPSET about how good that was!",
        "Great move! The commentator reluctantly admits the opponent has some skill. SOME.",
        "Impressive! You'd almost think YOU were the main character of this game! You're NOT, but almost!",
        "Well played! I'll allow it. Not that I could STOP it, but I'm ALLOWING it.",
        "That was solid! I'm putting a note in my book about you. Chapter seven: 'Worthy Opponents.' It's a short chapter.",
      ],
      blunder: [
        "That was... AVANT-GARDE chess. You wouldn't understand. I barely understand. Nobody understands.",
        "A BOLD move by Raj! Unconventional! Revolutionary! ...Possibly terrible! But BOLD!",
        "That was a SACRIFICE. For CONTENT. My future YouTube channel will THANK me.",
        "Raj makes a controversial move! The pundits will DEBATE this for years! The pundits are my cousin. He'll mention it at dinner.",
        "A slight miscalculation but Raj PIVOTS! Raj ADAPTS! Raj is PANICKING but doing it with STYLE!",
        "EXPERIMENTAL chess from Raj! When you're this talented you can AFFORD to take risks! I cannot afford it but I'm DOING it!",
      ],
      draw: [
        "A draw! Both players walk away with their dignity! Mostly! MINE mostly!",
        "The epic clash ends in a TIE! The crowd is SATISFIED! There is no crowd! I am SOMEWHAT satisfied!",
        "A draw! I'll take it! I'll put it on the RESUME! 'Did not lose to random internet stranger.' Very impressive.",
        "Neither of us won, but let the record show that Raj was WINNING for most of it. Spiritually.",
      ],
    },
};
